INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/templatetags/socialaccount.py", line 21, in provider_login_url
    provider = adapter.get_provider(request, provider)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/adapter.py", line 211, in get_provider
    app = self.get_app(request, provider=provider)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/adapter.py", line 296, in get_app
    raise MultipleObjectsReturned
django.core.exceptions.MultipleObjectsReturned
ERROR:django.request:Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/templatetags/socialaccount.py", line 21, in provider_login_url
    provider = adapter.get_provider(request, provider)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/adapter.py", line 211, in get_provider
    app = self.get_app(request, provider=provider)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/adapter.py", line 296, in get_app
    raise MultipleObjectsReturned
django.core.exceptions.MultipleObjectsReturned
ERROR:django.request:Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/templatetags/socialaccount.py", line 21, in provider_login_url
    provider = adapter.get_provider(request, provider)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/adapter.py", line 211, in get_provider
    app = self.get_app(request, provider=provider)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/adapter.py", line 296, in get_app
    raise MultipleObjectsReturned
django.core.exceptions.MultipleObjectsReturned
ERROR:django.request:Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/templatetags/socialaccount.py", line 21, in provider_login_url
    provider = adapter.get_provider(request, provider)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/adapter.py", line 211, in get_provider
    app = self.get_app(request, provider=provider)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/adapter.py", line 296, in get_app
    raise MultipleObjectsReturned
django.core.exceptions.MultipleObjectsReturned
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/templatetags/socialaccount.py", line 21, in provider_login_url
    provider = adapter.get_provider(request, provider)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/adapter.py", line 211, in get_provider
    app = self.get_app(request, provider=provider)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/adapter.py", line 296, in get_app
    raise MultipleObjectsReturned
django.core.exceptions.MultipleObjectsReturned
ERROR:django.request:Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/templatetags/socialaccount.py", line 21, in provider_login_url
    provider = adapter.get_provider(request, provider)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/adapter.py", line 211, in get_provider
    app = self.get_app(request, provider=provider)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/adapter.py", line 296, in get_app
    raise MultipleObjectsReturned
django.core.exceptions.MultipleObjectsReturned
ERROR:django.request:Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/templatetags/socialaccount.py", line 21, in provider_login_url
    provider = adapter.get_provider(request, provider)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/adapter.py", line 211, in get_provider
    app = self.get_app(request, provider=provider)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/adapter.py", line 296, in get_app
    raise MultipleObjectsReturned
django.core.exceptions.MultipleObjectsReturned
ERROR:django.request:Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/templatetags/socialaccount.py", line 21, in provider_login_url
    provider = adapter.get_provider(request, provider)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/adapter.py", line 211, in get_provider
    app = self.get_app(request, provider=provider)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/adapter.py", line 296, in get_app
    raise MultipleObjectsReturned
django.core.exceptions.MultipleObjectsReturned
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /categories/
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:Current server time: 2024-05-11 13:25:05.220886
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:Current server time: 2024-05-11 13:28:23.949202
INFO:root:Current server time: 2024-05-11 13:28:55.633622
INFO:root:Current server time: 2024-05-11 13:29:29.640086
INFO:root:Current server time: 2024-05-11 13:29:42.552353
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.security.csrf:Forbidden (Origin checking failed - https://5258-115-74-83-222.ngrok-free.app does not match any trusted origins.): /accounts/facebook/login/
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:Current server time: 2024-05-11 13:36:13.561928
INFO:django.utils.autoreload:/Users/huy/code/project/api/urls.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/api/urls.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/api/urls.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/app/urls.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:Current server time: 2024-05-11 13:54:48.722424
INFO:root:Current server time: 2024-05-11 13:54:56.032107
INFO:root:Current server time: 2024-05-11 13:55:00.428715
INFO:django.utils.autoreload:/Users/huy/code/project/app/my_middleware.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/app/my_middleware.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/app/my_middleware.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQAelx-Rs2qLr2LrKvW7-MLfNDu8rznAwX5gN9wl7i19iosGFiKPc9ruYV7KQDdHpxr9kMwh_hPx9zx5g6fk-AB3ooOyT4StaXtl9_PKIBVh1YmqDAKMnJalLlKbsWGab5MK2rSIhFkaCWZH4BYY9CVVaGEYuejjOOaRD35o5hOa_lhZ4NPvxP8Dbj-5wWxJXsE1SAuXlAzk0wbLlnLlTrzvtPH3A4jmCjWN-fAiMWpT-krznxRTrcpUoNc7kNIfCetqdVylYcuwmSZEciCpgYOpknt2aUULmP72Q_yAARkf5dcDXfnaqtqHd1ozBSJKE6jkhUDT4qaDtP0F2lfbG3xYhEzlZff672DQebghPVTgqewZpHD96tcWcP4mpcjTU9o
INFO:app.my_middleware:Facebook callback received with code: AQCGwAkxSxZTAcWsD3Gb5moGOQjtk51u0eQyZgMKv-fl6vclPDc3wC0I2Pn6qBl81S33Q1LaaqYVYf9pt-UnYal36626uAqEAQ62w-cEKYGfJxFdyHXw-uRZd_RFRLQDfxN53XnHq6fTJxjp9BQvDi9MnLGlUwLG8Fda1xzoUDSSMUFh8vsxm2Nxpu5lPgVZZBnvdVrZa8M_us2jIScMB7J3DgneyyViosbR3990B0u7kwUePL6MZqscDIXh_ideT9RLxZjsQqUrWXuAnPA9vIqCB847-XlM6tH4aCtPTy2kvsjv3jJIc6qQqmTqWvzsGfCRXUlQgtkGWtL_QdYUMInw05fin2fGMWmWUzq7MHIDrDm7J8GaDraaeBTkNX3mAgM
INFO:django.utils.autoreload:/Users/huy/code/project/app/my_middleware.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQCGwAkxSxZTAcWsD3Gb5moGOQjtk51u0eQyZgMKv-fl6vclPDc3wC0I2Pn6qBl81S33Q1LaaqYVYf9pt-UnYal36626uAqEAQ62w-cEKYGfJxFdyHXw-uRZd_RFRLQDfxN53XnHq6fTJxjp9BQvDi9MnLGlUwLG8Fda1xzoUDSSMUFh8vsxm2Nxpu5lPgVZZBnvdVrZa8M_us2jIScMB7J3DgneyyViosbR3990B0u7kwUePL6MZqscDIXh_ideT9RLxZjsQqUrWXuAnPA9vIqCB847-XlM6tH4aCtPTy2kvsjv3jJIc6qQqmTqWvzsGfCRXUlQgtkGWtL_QdYUMInw05fin2fGMWmWUzq7MHIDrDm7J8GaDraaeBTkNX3mAgM
INFO:app.my_middleware:Facebook callback received with code: AQCGwAkxSxZTAcWsD3Gb5moGOQjtk51u0eQyZgMKv-fl6vclPDc3wC0I2Pn6qBl81S33Q1LaaqYVYf9pt-UnYal36626uAqEAQ62w-cEKYGfJxFdyHXw-uRZd_RFRLQDfxN53XnHq6fTJxjp9BQvDi9MnLGlUwLG8Fda1xzoUDSSMUFh8vsxm2Nxpu5lPgVZZBnvdVrZa8M_us2jIScMB7J3DgneyyViosbR3990B0u7kwUePL6MZqscDIXh_ideT9RLxZjsQqUrWXuAnPA9vIqCB847-XlM6tH4aCtPTy2kvsjv3jJIc6qQqmTqWvzsGfCRXUlQgtkGWtL_QdYUMInw05fin2fGMWmWUzq7MHIDrDm7J8GaDraaeBTkNX3mAgM
INFO:django.utils.autoreload:/Users/huy/code/project/app/my_middleware.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQCGwAkxSxZTAcWsD3Gb5moGOQjtk51u0eQyZgMKv-fl6vclPDc3wC0I2Pn6qBl81S33Q1LaaqYVYf9pt-UnYal36626uAqEAQ62w-cEKYGfJxFdyHXw-uRZd_RFRLQDfxN53XnHq6fTJxjp9BQvDi9MnLGlUwLG8Fda1xzoUDSSMUFh8vsxm2Nxpu5lPgVZZBnvdVrZa8M_us2jIScMB7J3DgneyyViosbR3990B0u7kwUePL6MZqscDIXh_ideT9RLxZjsQqUrWXuAnPA9vIqCB847-XlM6tH4aCtPTy2kvsjv3jJIc6qQqmTqWvzsGfCRXUlQgtkGWtL_QdYUMInw05fin2fGMWmWUzq7MHIDrDm7J8GaDraaeBTkNX3mAgM
INFO:app.my_middleware:Facebook callback received with code: AQAixZNSjmNJ5WlnBCglAPcXvEn0XFwLoVXAixyvG5Y-0HoudjoPAbHELkuP1kQFXlnK2STA6HVXnJz8PJBBhUerye8QVT-zHdhaj8pkVaXVSMWenKP_SDpb3b0A2_9UaP32jd5Od-dthPkISQOLBFU23irVUqzLVCKEChCWkuFDII0YvyXTvME6sRpY-2hl9C9inaMb-0eCssMHlB8o95Aue6axH5Ia3IjucUC9T0fLvZmF-5YCxVF24cQ6MNxFLiOQx1vnmf3QjEdvDJjmVogz_p-WCdi4Si_TvLqAUXImrT3nGlf_Ro-5kKeghAFI_IffTMr8cSc2HmVxXO9CKs9o-isXx56S0JzlqcoJf7rzYXVDXipjIUNGTDeCL1GGNH4
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQAixZNSjmNJ5WlnBCglAPcXvEn0XFwLoVXAixyvG5Y-0HoudjoPAbHELkuP1kQFXlnK2STA6HVXnJz8PJBBhUerye8QVT-zHdhaj8pkVaXVSMWenKP_SDpb3b0A2_9UaP32jd5Od-dthPkISQOLBFU23irVUqzLVCKEChCWkuFDII0YvyXTvME6sRpY-2hl9C9inaMb-0eCssMHlB8o95Aue6axH5Ia3IjucUC9T0fLvZmF-5YCxVF24cQ6MNxFLiOQx1vnmf3QjEdvDJjmVogz_p-WCdi4Si_TvLqAUXImrT3nGlf_Ro-5kKeghAFI_IffTMr8cSc2HmVxXO9CKs9o-isXx56S0JzlqcoJf7rzYXVDXipjIUNGTDeCL1GGNH4
INFO:app.my_middleware:Facebook callback received with code: AQAixZNSjmNJ5WlnBCglAPcXvEn0XFwLoVXAixyvG5Y-0HoudjoPAbHELkuP1kQFXlnK2STA6HVXnJz8PJBBhUerye8QVT-zHdhaj8pkVaXVSMWenKP_SDpb3b0A2_9UaP32jd5Od-dthPkISQOLBFU23irVUqzLVCKEChCWkuFDII0YvyXTvME6sRpY-2hl9C9inaMb-0eCssMHlB8o95Aue6axH5Ia3IjucUC9T0fLvZmF-5YCxVF24cQ6MNxFLiOQx1vnmf3QjEdvDJjmVogz_p-WCdi4Si_TvLqAUXImrT3nGlf_Ro-5kKeghAFI_IffTMr8cSc2HmVxXO9CKs9o-isXx56S0JzlqcoJf7rzYXVDXipjIUNGTDeCL1GGNH4
INFO:app.my_middleware:Facebook callback received with code: AQB6F-4NdkBb3qB7CKIPyRPmXwJH2Zi5O8dKEZAwrgsfeNhGbdXvIUb_998G5pIMEmiP3MeX3es_M6erKi3gmgqPw8Nq4yvueBh_uRMkEh3bYbDqfBqH8wobvA2ahgpz_lblCP07_uLZu7c69peF7qgmw4HnrFICAkNopyU35V86XpJYk7gR1cXD3yzLthBqjWyRaxjwEGcTlwifM6tbAAPFTHq0hZq5DEiBWyEccPM8GBEgPMzI4wY0-aql1Hq9TBMKxhOkeUQxyePxAcVNKidySbJVEQsSdhZoReXKXeAW_M9FR8yfsbtrLB6FID3dJ-XcCIcYRtIacOjOxo1RIsvHryxezGikHj7r6WiS1vD7SMpvMl3XnySTMBopl0GdrcQ
INFO:root:Current server time: 2024-05-11 14:12:54.520310
INFO:root:Current server time: 2024-05-11 14:12:56.086542
INFO:app.my_middleware:Facebook callback received with code: AQCb6YKxRR5TXmWMc7LJABZot62qjAUQKiUSzw3EuU4jY1RjgUAcy7i0dxiCSVEWHWjQsd90BP1s9gHB0nHDDWaHImuiD252HNipbUM8kNjYpM8LX7JGBNymo0KWO0qAw2qGo9hWBON2BjPRHkD0c34yHDHgdf_MuQMUThMASuMd__INSYYb4NDhm0vcGaUZiesXlyBwfJZJBNibnpvDO6oX8uhUjwXqskKfdxUmm7nIgOEVTB-8vYmAJW-ivQiLbhvopCvpDpVYnjtWCouzYqbV92fKxhITSP4wQHb7Il6VCDO60nY31GNVSJE6qLzqQs-ZDILqb9fAXo966dGsoJOrbv9DpjKPj26oW5wqUG2CkkPlWU2bAhOiKe6JFbXa-pESCfE-7zyd2qSvSWaqvTmf01t-hhonzEsrRnsY8wpglQ
INFO:root:Current server time: 2024-05-11 14:13:12.813306
INFO:root:Current server time: 2024-05-11 14:13:14.674986
INFO:root:Current server time: 2024-05-11 14:13:15.123272
INFO:app.my_middleware:Facebook callback received with code: AQCxq9AncgXUpWiU5JT2zOUTGb59qUtnjD90m0aARBNgxzMWBlvMjyUulVXxBjyXM4H-9vwQYJA1NsKBre4rf6u9Tj8eY0iZBNRKcRLhTinwLwdotRAgLi2pwvPvFJDHwBNLgEL_pMxImqF9NyoJolRMBsIUgjXbMn_xWd7T3f0KSv9pdn823TNEgWg3RgQAcMtBkvC0gIRedkUgGiCkp0Flssruy0z7n5Dr6RGTCkOjanvdvD5F8AfJpSkfJu-3geeIjE5Rthr6lOCKKJOy3_GGtFf5sKRVgolHmrgF1h2GdlH_C0Ezk6VyickpA5LBcdDma4C2XeFbz6iUFrcPkxYml7WJ9lCMRbjqwCc-pOgSNVYFbVajE1udtmKgDdFdIN5noOoKHlPbIisVaKrPOac0kSQ5Ccqt34kRy8Fg9hQKrw
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQCxq9AncgXUpWiU5JT2zOUTGb59qUtnjD90m0aARBNgxzMWBlvMjyUulVXxBjyXM4H-9vwQYJA1NsKBre4rf6u9Tj8eY0iZBNRKcRLhTinwLwdotRAgLi2pwvPvFJDHwBNLgEL_pMxImqF9NyoJolRMBsIUgjXbMn_xWd7T3f0KSv9pdn823TNEgWg3RgQAcMtBkvC0gIRedkUgGiCkp0Flssruy0z7n5Dr6RGTCkOjanvdvD5F8AfJpSkfJu-3geeIjE5Rthr6lOCKKJOy3_GGtFf5sKRVgolHmrgF1h2GdlH_C0Ezk6VyickpA5LBcdDma4C2XeFbz6iUFrcPkxYml7WJ9lCMRbjqwCc-pOgSNVYFbVajE1udtmKgDdFdIN5noOoKHlPbIisVaKrPOac0kSQ5Ccqt34kRy8Fg9hQKrw
INFO:app.my_middleware:Facebook callback received with code: AQABqHUzEZQk8KlEVBgtbmpJZTs-9vKbJbKwBjl7SC8YwDmdpVMTiEqDX86jzad2wOQ3oPd2eNa7oYP60nuAt1WH1pcoA7rxdB1F_fFwrUkoq0vIQyCeIJ4PfXheXacV_IVpxXbvrwODNmVip0CQ6TfrBQcYgVmkjOl0oxSsp3sjaqccLceSWIq3TXvDXvmE5ERkixyXyUbweKxMIJACwoBC-a3Hbgb1y9oUsW1rjKrNl0_DWZI8OYEUvNSYwghBUyWEC_Z5KqZB4ybF52CbIjPnBL2W6ctkSzE9FIEhNPUKWOBl54tZlXcabbPVrVnjQ4qKkxTTSXlVYk3TwfpkUdqQ8E2A1OmO0bhgOWSeN0i_lX-wKh5q9HgJmRJreAcaQJjEL1V9eWhvGB0zZiWBXAw5G5TeGpURvBFnh-Ywoo_C0g
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQABqHUzEZQk8KlEVBgtbmpJZTs-9vKbJbKwBjl7SC8YwDmdpVMTiEqDX86jzad2wOQ3oPd2eNa7oYP60nuAt1WH1pcoA7rxdB1F_fFwrUkoq0vIQyCeIJ4PfXheXacV_IVpxXbvrwODNmVip0CQ6TfrBQcYgVmkjOl0oxSsp3sjaqccLceSWIq3TXvDXvmE5ERkixyXyUbweKxMIJACwoBC-a3Hbgb1y9oUsW1rjKrNl0_DWZI8OYEUvNSYwghBUyWEC_Z5KqZB4ybF52CbIjPnBL2W6ctkSzE9FIEhNPUKWOBl54tZlXcabbPVrVnjQ4qKkxTTSXlVYk3TwfpkUdqQ8E2A1OmO0bhgOWSeN0i_lX-wKh5q9HgJmRJreAcaQJjEL1V9eWhvGB0zZiWBXAw5G5TeGpURvBFnh-Ywoo_C0g
INFO:app.my_middleware:Facebook callback received with code: AQABqHUzEZQk8KlEVBgtbmpJZTs-9vKbJbKwBjl7SC8YwDmdpVMTiEqDX86jzad2wOQ3oPd2eNa7oYP60nuAt1WH1pcoA7rxdB1F_fFwrUkoq0vIQyCeIJ4PfXheXacV_IVpxXbvrwODNmVip0CQ6TfrBQcYgVmkjOl0oxSsp3sjaqccLceSWIq3TXvDXvmE5ERkixyXyUbweKxMIJACwoBC-a3Hbgb1y9oUsW1rjKrNl0_DWZI8OYEUvNSYwghBUyWEC_Z5KqZB4ybF52CbIjPnBL2W6ctkSzE9FIEhNPUKWOBl54tZlXcabbPVrVnjQ4qKkxTTSXlVYk3TwfpkUdqQ8E2A1OmO0bhgOWSeN0i_lX-wKh5q9HgJmRJreAcaQJjEL1V9eWhvGB0zZiWBXAw5G5TeGpURvBFnh-Ywoo_C0g
INFO:app.my_middleware:Facebook callback received with code: AQC0-Ow5bFB_VWo8NHSL0S3kKxRvMN0GqUq6Pvk9EuGNuA8Rw2gUgkZzmee6HCSN8fV2DmLXX0WcthqYw5Bgj_oOQlrDkDdmYBYuCfQL0k3VhrUjNEcbcsrGfURTbIgNEa4YRdDdwjqVeE2DFsJWnCxdXMYlJmjd_Ecl4YOBChtervlj5oD9ocFwXqsQAvQXrlcA-SRPHm-Fq7DoWuhddkz3r3vVC3HV1Oid0VsumniiP8Cd6Bpc5XE8Qw_lnqQWhiraStvHUr657P6LnZoaVavrRrsCNKeqfq7v9yzcKZdNHNe2fQNs34YPEhPuP2sTRrfXT75NBZ5ICQyFDDrQheeO9pPWzSJY6_0CbbE7EJKptEreQPEY_RHeA_WWNZ6wVwnf2gx6jeShOL2ftctJ8Vn-d8BdQXJ5y-r9AeEvNseDIQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC0-Ow5bFB_VWo8NHSL0S3kKxRvMN0GqUq6Pvk9EuGNuA8Rw2gUgkZzmee6HCSN8fV2DmLXX0WcthqYw5Bgj_oOQlrDkDdmYBYuCfQL0k3VhrUjNEcbcsrGfURTbIgNEa4YRdDdwjqVeE2DFsJWnCxdXMYlJmjd_Ecl4YOBChtervlj5oD9ocFwXqsQAvQXrlcA-SRPHm-Fq7DoWuhddkz3r3vVC3HV1Oid0VsumniiP8Cd6Bpc5XE8Qw_lnqQWhiraStvHUr657P6LnZoaVavrRrsCNKeqfq7v9yzcKZdNHNe2fQNs34YPEhPuP2sTRrfXT75NBZ5ICQyFDDrQheeO9pPWzSJY6_0CbbE7EJKptEreQPEY_RHeA_WWNZ6wVwnf2gx6jeShOL2ftctJ8Vn-d8BdQXJ5y-r9AeEvNseDIQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC0-Ow5bFB_VWo8NHSL0S3kKxRvMN0GqUq6Pvk9EuGNuA8Rw2gUgkZzmee6HCSN8fV2DmLXX0WcthqYw5Bgj_oOQlrDkDdmYBYuCfQL0k3VhrUjNEcbcsrGfURTbIgNEa4YRdDdwjqVeE2DFsJWnCxdXMYlJmjd_Ecl4YOBChtervlj5oD9ocFwXqsQAvQXrlcA-SRPHm-Fq7DoWuhddkz3r3vVC3HV1Oid0VsumniiP8Cd6Bpc5XE8Qw_lnqQWhiraStvHUr657P6LnZoaVavrRrsCNKeqfq7v9yzcKZdNHNe2fQNs34YPEhPuP2sTRrfXT75NBZ5ICQyFDDrQheeO9pPWzSJY6_0CbbE7EJKptEreQPEY_RHeA_WWNZ6wVwnf2gx6jeShOL2ftctJ8Vn-d8BdQXJ5y-r9AeEvNseDIQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/app/my_middleware.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC0-Ow5bFB_VWo8NHSL0S3kKxRvMN0GqUq6Pvk9EuGNuA8Rw2gUgkZzmee6HCSN8fV2DmLXX0WcthqYw5Bgj_oOQlrDkDdmYBYuCfQL0k3VhrUjNEcbcsrGfURTbIgNEa4YRdDdwjqVeE2DFsJWnCxdXMYlJmjd_Ecl4YOBChtervlj5oD9ocFwXqsQAvQXrlcA-SRPHm-Fq7DoWuhddkz3r3vVC3HV1Oid0VsumniiP8Cd6Bpc5XE8Qw_lnqQWhiraStvHUr657P6LnZoaVavrRrsCNKeqfq7v9yzcKZdNHNe2fQNs34YPEhPuP2sTRrfXT75NBZ5ICQyFDDrQheeO9pPWzSJY6_0CbbE7EJKptEreQPEY_RHeA_WWNZ6wVwnf2gx6jeShOL2ftctJ8Vn-d8BdQXJ5y-r9AeEvNseDIQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC0-Ow5bFB_VWo8NHSL0S3kKxRvMN0GqUq6Pvk9EuGNuA8Rw2gUgkZzmee6HCSN8fV2DmLXX0WcthqYw5Bgj_oOQlrDkDdmYBYuCfQL0k3VhrUjNEcbcsrGfURTbIgNEa4YRdDdwjqVeE2DFsJWnCxdXMYlJmjd_Ecl4YOBChtervlj5oD9ocFwXqsQAvQXrlcA-SRPHm-Fq7DoWuhddkz3r3vVC3HV1Oid0VsumniiP8Cd6Bpc5XE8Qw_lnqQWhiraStvHUr657P6LnZoaVavrRrsCNKeqfq7v9yzcKZdNHNe2fQNs34YPEhPuP2sTRrfXT75NBZ5ICQyFDDrQheeO9pPWzSJY6_0CbbE7EJKptEreQPEY_RHeA_WWNZ6wVwnf2gx6jeShOL2ftctJ8Vn-d8BdQXJ5y-r9AeEvNseDIQ
INFO:app.my_middleware:Facebook callback received with code: AQC0-Ow5bFB_VWo8NHSL0S3kKxRvMN0GqUq6Pvk9EuGNuA8Rw2gUgkZzmee6HCSN8fV2DmLXX0WcthqYw5Bgj_oOQlrDkDdmYBYuCfQL0k3VhrUjNEcbcsrGfURTbIgNEa4YRdDdwjqVeE2DFsJWnCxdXMYlJmjd_Ecl4YOBChtervlj5oD9ocFwXqsQAvQXrlcA-SRPHm-Fq7DoWuhddkz3r3vVC3HV1Oid0VsumniiP8Cd6Bpc5XE8Qw_lnqQWhiraStvHUr657P6LnZoaVavrRrsCNKeqfq7v9yzcKZdNHNe2fQNs34YPEhPuP2sTRrfXT75NBZ5ICQyFDDrQheeO9pPWzSJY6_0CbbE7EJKptEreQPEY_RHeA_WWNZ6wVwnf2gx6jeShOL2ftctJ8Vn-d8BdQXJ5y-r9AeEvNseDIQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC0-Ow5bFB_VWo8NHSL0S3kKxRvMN0GqUq6Pvk9EuGNuA8Rw2gUgkZzmee6HCSN8fV2DmLXX0WcthqYw5Bgj_oOQlrDkDdmYBYuCfQL0k3VhrUjNEcbcsrGfURTbIgNEa4YRdDdwjqVeE2DFsJWnCxdXMYlJmjd_Ecl4YOBChtervlj5oD9ocFwXqsQAvQXrlcA-SRPHm-Fq7DoWuhddkz3r3vVC3HV1Oid0VsumniiP8Cd6Bpc5XE8Qw_lnqQWhiraStvHUr657P6LnZoaVavrRrsCNKeqfq7v9yzcKZdNHNe2fQNs34YPEhPuP2sTRrfXT75NBZ5ICQyFDDrQheeO9pPWzSJY6_0CbbE7EJKptEreQPEY_RHeA_WWNZ6wVwnf2gx6jeShOL2ftctJ8Vn-d8BdQXJ5y-r9AeEvNseDIQ
INFO:app.my_middleware:Facebook callback received with code: AQC0-Ow5bFB_VWo8NHSL0S3kKxRvMN0GqUq6Pvk9EuGNuA8Rw2gUgkZzmee6HCSN8fV2DmLXX0WcthqYw5Bgj_oOQlrDkDdmYBYuCfQL0k3VhrUjNEcbcsrGfURTbIgNEa4YRdDdwjqVeE2DFsJWnCxdXMYlJmjd_Ecl4YOBChtervlj5oD9ocFwXqsQAvQXrlcA-SRPHm-Fq7DoWuhddkz3r3vVC3HV1Oid0VsumniiP8Cd6Bpc5XE8Qw_lnqQWhiraStvHUr657P6LnZoaVavrRrsCNKeqfq7v9yzcKZdNHNe2fQNs34YPEhPuP2sTRrfXT75NBZ5ICQyFDDrQheeO9pPWzSJY6_0CbbE7EJKptEreQPEY_RHeA_WWNZ6wVwnf2gx6jeShOL2ftctJ8Vn-d8BdQXJ5y-r9AeEvNseDIQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC0-Ow5bFB_VWo8NHSL0S3kKxRvMN0GqUq6Pvk9EuGNuA8Rw2gUgkZzmee6HCSN8fV2DmLXX0WcthqYw5Bgj_oOQlrDkDdmYBYuCfQL0k3VhrUjNEcbcsrGfURTbIgNEa4YRdDdwjqVeE2DFsJWnCxdXMYlJmjd_Ecl4YOBChtervlj5oD9ocFwXqsQAvQXrlcA-SRPHm-Fq7DoWuhddkz3r3vVC3HV1Oid0VsumniiP8Cd6Bpc5XE8Qw_lnqQWhiraStvHUr657P6LnZoaVavrRrsCNKeqfq7v9yzcKZdNHNe2fQNs34YPEhPuP2sTRrfXT75NBZ5ICQyFDDrQheeO9pPWzSJY6_0CbbE7EJKptEreQPEY_RHeA_WWNZ6wVwnf2gx6jeShOL2ftctJ8Vn-d8BdQXJ5y-r9AeEvNseDIQ
ERROR:django.request:Internal Server Error: /accounts/facebook/login/callback/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 102, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 146, in dispatch
    request, app, client, pkce_code_verifier=state.get("pkce_code_verifier")
                                             ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
INFO:app.my_middleware:Facebook callback received with code: AQC0-Ow5bFB_VWo8NHSL0S3kKxRvMN0GqUq6Pvk9EuGNuA8Rw2gUgkZzmee6HCSN8fV2DmLXX0WcthqYw5Bgj_oOQlrDkDdmYBYuCfQL0k3VhrUjNEcbcsrGfURTbIgNEa4YRdDdwjqVeE2DFsJWnCxdXMYlJmjd_Ecl4YOBChtervlj5oD9ocFwXqsQAvQXrlcA-SRPHm-Fq7DoWuhddkz3r3vVC3HV1Oid0VsumniiP8Cd6Bpc5XE8Qw_lnqQWhiraStvHUr657P6LnZoaVavrRrsCNKeqfq7v9yzcKZdNHNe2fQNs34YPEhPuP2sTRrfXT75NBZ5ICQyFDDrQheeO9pPWzSJY6_0CbbE7EJKptEreQPEY_RHeA_WWNZ6wVwnf2gx6jeShOL2ftctJ8Vn-d8BdQXJ5y-r9AeEvNseDIQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC0-Ow5bFB_VWo8NHSL0S3kKxRvMN0GqUq6Pvk9EuGNuA8Rw2gUgkZzmee6HCSN8fV2DmLXX0WcthqYw5Bgj_oOQlrDkDdmYBYuCfQL0k3VhrUjNEcbcsrGfURTbIgNEa4YRdDdwjqVeE2DFsJWnCxdXMYlJmjd_Ecl4YOBChtervlj5oD9ocFwXqsQAvQXrlcA-SRPHm-Fq7DoWuhddkz3r3vVC3HV1Oid0VsumniiP8Cd6Bpc5XE8Qw_lnqQWhiraStvHUr657P6LnZoaVavrRrsCNKeqfq7v9yzcKZdNHNe2fQNs34YPEhPuP2sTRrfXT75NBZ5ICQyFDDrQheeO9pPWzSJY6_0CbbE7EJKptEreQPEY_RHeA_WWNZ6wVwnf2gx6jeShOL2ftctJ8Vn-d8BdQXJ5y-r9AeEvNseDIQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC0-Ow5bFB_VWo8NHSL0S3kKxRvMN0GqUq6Pvk9EuGNuA8Rw2gUgkZzmee6HCSN8fV2DmLXX0WcthqYw5Bgj_oOQlrDkDdmYBYuCfQL0k3VhrUjNEcbcsrGfURTbIgNEa4YRdDdwjqVeE2DFsJWnCxdXMYlJmjd_Ecl4YOBChtervlj5oD9ocFwXqsQAvQXrlcA-SRPHm-Fq7DoWuhddkz3r3vVC3HV1Oid0VsumniiP8Cd6Bpc5XE8Qw_lnqQWhiraStvHUr657P6LnZoaVavrRrsCNKeqfq7v9yzcKZdNHNe2fQNs34YPEhPuP2sTRrfXT75NBZ5ICQyFDDrQheeO9pPWzSJY6_0CbbE7EJKptEreQPEY_RHeA_WWNZ6wVwnf2gx6jeShOL2ftctJ8Vn-d8BdQXJ5y-r9AeEvNseDIQ
INFO:app.my_middleware:Facebook callback received with code: AQC0-Ow5bFB_VWo8NHSL0S3kKxRvMN0GqUq6Pvk9EuGNuA8Rw2gUgkZzmee6HCSN8fV2DmLXX0WcthqYw5Bgj_oOQlrDkDdmYBYuCfQL0k3VhrUjNEcbcsrGfURTbIgNEa4YRdDdwjqVeE2DFsJWnCxdXMYlJmjd_Ecl4YOBChtervlj5oD9ocFwXqsQAvQXrlcA-SRPHm-Fq7DoWuhddkz3r3vVC3HV1Oid0VsumniiP8Cd6Bpc5XE8Qw_lnqQWhiraStvHUr657P6LnZoaVavrRrsCNKeqfq7v9yzcKZdNHNe2fQNs34YPEhPuP2sTRrfXT75NBZ5ICQyFDDrQheeO9pPWzSJY6_0CbbE7EJKptEreQPEY_RHeA_WWNZ6wVwnf2gx6jeShOL2ftctJ8Vn-d8BdQXJ5y-r9AeEvNseDIQ
INFO:root:Current server time: 2024-05-11 14:30:01.886864
INFO:app.my_middleware:Facebook callback received with code: AQCO3fTbUdMRJxoqnMevhe7bCnpB8_bEVooVeG7G5hBfuNl9fhfNNBiPVn2x204RIORCpqvLtwXGQTnrpcqzZ6pxwspsP9I5zM2T1y8t7OqX-VHPY5q_ggKXNd0a_0XiedKQ1-tEaVTRuLnQOeloSH1iMBfZgo8MMhWhitV00poz0Zv_mJ9h6XmeKRp8JRlV4J4fZAaEYzw0SUR_J-lWd1PHSlurnhfSbp1NFHmKZIgHxter5Pm2u3yumzb_YruurG4o6UkFmhIBnhCyGGxQI2IBq1PDGyY5v3L0gt1Dkvk7mmxiX4nlB9i8uXoxX5DCXvbQNUBlny7wqTId2ab1siitibOzRt5ihADcVDa6MKYWORJ9It4j-yCE9gULE3gEMGCZ6n4wl1bq9RVxK03CAeMCFTQoQ0pYoyLf6GenOyyaaA
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC-85cnlwAlT1t0wHaMl8ipHH_X_JjTsqOvq07YGJcbg46cxtm8pdaf8ThnyNl1V3dHMMdUyStnczjSpBvtxTSutReVkFonKQlaYr1pwRTeDesTP1LGAQk_riFLmu2UFo_VUvWKZV-QRI_HQno4oRWIajocb_v-_Yx_Ltx3cmlKT9_Nlx42rTqtlOuBDW49Pfnc9GpR2tXDGXhQDP_rMrLuQlv4jlqI-LpVEgJRyudKxfdkTCDgxRf_YMEK74lw0v-ZgI3nypQpIWJ4Mbti7nYQapVnQzVlEbY-GdZ8krSflLyDOTfYeIK0KPsBAVBIoGXu5CfmLKu1p2LfYOIE60AaSOpCkcrCW4kBeY2XKZJF0bnCxv7qeSS0MIYTyEXgVGe3uaK3--VgCinHLr7_nVQittX2X0Cd6svVrSg5J58r_Q
ERROR:django.request:Internal Server Error: /accounts/facebook/login/callback/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 102, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 147, in dispatch
    request, app, client, pkce_code_verifier=state.get("pkce_code_verifier")
                                             ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC-85cnlwAlT1t0wHaMl8ipHH_X_JjTsqOvq07YGJcbg46cxtm8pdaf8ThnyNl1V3dHMMdUyStnczjSpBvtxTSutReVkFonKQlaYr1pwRTeDesTP1LGAQk_riFLmu2UFo_VUvWKZV-QRI_HQno4oRWIajocb_v-_Yx_Ltx3cmlKT9_Nlx42rTqtlOuBDW49Pfnc9GpR2tXDGXhQDP_rMrLuQlv4jlqI-LpVEgJRyudKxfdkTCDgxRf_YMEK74lw0v-ZgI3nypQpIWJ4Mbti7nYQapVnQzVlEbY-GdZ8krSflLyDOTfYeIK0KPsBAVBIoGXu5CfmLKu1p2LfYOIE60AaSOpCkcrCW4kBeY2XKZJF0bnCxv7qeSS0MIYTyEXgVGe3uaK3--VgCinHLr7_nVQittX2X0Cd6svVrSg5J58r_Q
ERROR:django.request:Internal Server Error: /accounts/facebook/login/callback/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 102, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 121, in dispatch
    print('state.get("pkce_code_verifier")',state.get("pkce_code_verifier"))
                                            ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC-85cnlwAlT1t0wHaMl8ipHH_X_JjTsqOvq07YGJcbg46cxtm8pdaf8ThnyNl1V3dHMMdUyStnczjSpBvtxTSutReVkFonKQlaYr1pwRTeDesTP1LGAQk_riFLmu2UFo_VUvWKZV-QRI_HQno4oRWIajocb_v-_Yx_Ltx3cmlKT9_Nlx42rTqtlOuBDW49Pfnc9GpR2tXDGXhQDP_rMrLuQlv4jlqI-LpVEgJRyudKxfdkTCDgxRf_YMEK74lw0v-ZgI3nypQpIWJ4Mbti7nYQapVnQzVlEbY-GdZ8krSflLyDOTfYeIK0KPsBAVBIoGXu5CfmLKu1p2LfYOIE60AaSOpCkcrCW4kBeY2XKZJF0bnCxv7qeSS0MIYTyEXgVGe3uaK3--VgCinHLr7_nVQittX2X0Cd6svVrSg5J58r_Q
ERROR:django.request:Internal Server Error: /accounts/facebook/login/callback/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 102, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 121, in dispatch
    print('state.get("pkce_code_verifier")',state.get("pkce_code_verifier"))
                                            ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC-85cnlwAlT1t0wHaMl8ipHH_X_JjTsqOvq07YGJcbg46cxtm8pdaf8ThnyNl1V3dHMMdUyStnczjSpBvtxTSutReVkFonKQlaYr1pwRTeDesTP1LGAQk_riFLmu2UFo_VUvWKZV-QRI_HQno4oRWIajocb_v-_Yx_Ltx3cmlKT9_Nlx42rTqtlOuBDW49Pfnc9GpR2tXDGXhQDP_rMrLuQlv4jlqI-LpVEgJRyudKxfdkTCDgxRf_YMEK74lw0v-ZgI3nypQpIWJ4Mbti7nYQapVnQzVlEbY-GdZ8krSflLyDOTfYeIK0KPsBAVBIoGXu5CfmLKu1p2LfYOIE60AaSOpCkcrCW4kBeY2XKZJF0bnCxv7qeSS0MIYTyEXgVGe3uaK3--VgCinHLr7_nVQittX2X0Cd6svVrSg5J58r_Q
ERROR:django.request:Internal Server Error: /accounts/facebook/login/callback/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 102, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 121, in dispatch
    print('state.get("pkce_code_verifier")',state.get("pkce_code_verifier"))
                                            ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
INFO:app.my_middleware:Facebook callback received with code: AQC-85cnlwAlT1t0wHaMl8ipHH_X_JjTsqOvq07YGJcbg46cxtm8pdaf8ThnyNl1V3dHMMdUyStnczjSpBvtxTSutReVkFonKQlaYr1pwRTeDesTP1LGAQk_riFLmu2UFo_VUvWKZV-QRI_HQno4oRWIajocb_v-_Yx_Ltx3cmlKT9_Nlx42rTqtlOuBDW49Pfnc9GpR2tXDGXhQDP_rMrLuQlv4jlqI-LpVEgJRyudKxfdkTCDgxRf_YMEK74lw0v-ZgI3nypQpIWJ4Mbti7nYQapVnQzVlEbY-GdZ8krSflLyDOTfYeIK0KPsBAVBIoGXu5CfmLKu1p2LfYOIE60AaSOpCkcrCW4kBeY2XKZJF0bnCxv7qeSS0MIYTyEXgVGe3uaK3--VgCinHLr7_nVQittX2X0Cd6svVrSg5J58r_Q
ERROR:django.request:Internal Server Error: /accounts/facebook/login/callback/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 102, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 121, in dispatch
    if resp:
             
AttributeError: 'NoneType' object has no attribute 'get'
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQBPkuzxvvP86J_8vtcyXytK0RIDIRLqyB_GVWEa9FRqi7p5UKEbvljQo45-owOOiVI8FFaoKkRFsBPQxcMnEKOuiB1DnLu1L6Ky4AYNeDC0PUoKn1Z_lOS1qYIt93Xyc7XEASHQ6ttRs5VwnuKayGU9CUkVmIaNbxUcEBw7ol9vxHRjGJl3XIxCBy0te7zr6XZiddpaU3RlkzIc44yVxopXAxrkNMBVBD3K6sG3C7iFuaL3BBd9tqs4JaTXGOiqkCjsS-WwNTLBVY2KDsIFeLIhIBxBLaVC4te50conBKx45sU-cxl-p4tiB5tWUpcsj35OAa_5vKYdb17HGXBiP92h9sPg3wgMonBgZFo9PyUcOk-GMcefnNdoH1zYJF4fLg16EEyeY2INsjVgwUYSKHEND1lF6L-Habex7SVtCGr2JQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQBPkuzxvvP86J_8vtcyXytK0RIDIRLqyB_GVWEa9FRqi7p5UKEbvljQo45-owOOiVI8FFaoKkRFsBPQxcMnEKOuiB1DnLu1L6Ky4AYNeDC0PUoKn1Z_lOS1qYIt93Xyc7XEASHQ6ttRs5VwnuKayGU9CUkVmIaNbxUcEBw7ol9vxHRjGJl3XIxCBy0te7zr6XZiddpaU3RlkzIc44yVxopXAxrkNMBVBD3K6sG3C7iFuaL3BBd9tqs4JaTXGOiqkCjsS-WwNTLBVY2KDsIFeLIhIBxBLaVC4te50conBKx45sU-cxl-p4tiB5tWUpcsj35OAa_5vKYdb17HGXBiP92h9sPg3wgMonBgZFo9PyUcOk-GMcefnNdoH1zYJF4fLg16EEyeY2INsjVgwUYSKHEND1lF6L-Habex7SVtCGr2JQ
INFO:app.my_middleware:Facebook callback received with code: AQBPkuzxvvP86J_8vtcyXytK0RIDIRLqyB_GVWEa9FRqi7p5UKEbvljQo45-owOOiVI8FFaoKkRFsBPQxcMnEKOuiB1DnLu1L6Ky4AYNeDC0PUoKn1Z_lOS1qYIt93Xyc7XEASHQ6ttRs5VwnuKayGU9CUkVmIaNbxUcEBw7ol9vxHRjGJl3XIxCBy0te7zr6XZiddpaU3RlkzIc44yVxopXAxrkNMBVBD3K6sG3C7iFuaL3BBd9tqs4JaTXGOiqkCjsS-WwNTLBVY2KDsIFeLIhIBxBLaVC4te50conBKx45sU-cxl-p4tiB5tWUpcsj35OAa_5vKYdb17HGXBiP92h9sPg3wgMonBgZFo9PyUcOk-GMcefnNdoH1zYJF4fLg16EEyeY2INsjVgwUYSKHEND1lF6L-Habex7SVtCGr2JQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQBPkuzxvvP86J_8vtcyXytK0RIDIRLqyB_GVWEa9FRqi7p5UKEbvljQo45-owOOiVI8FFaoKkRFsBPQxcMnEKOuiB1DnLu1L6Ky4AYNeDC0PUoKn1Z_lOS1qYIt93Xyc7XEASHQ6ttRs5VwnuKayGU9CUkVmIaNbxUcEBw7ol9vxHRjGJl3XIxCBy0te7zr6XZiddpaU3RlkzIc44yVxopXAxrkNMBVBD3K6sG3C7iFuaL3BBd9tqs4JaTXGOiqkCjsS-WwNTLBVY2KDsIFeLIhIBxBLaVC4te50conBKx45sU-cxl-p4tiB5tWUpcsj35OAa_5vKYdb17HGXBiP92h9sPg3wgMonBgZFo9PyUcOk-GMcefnNdoH1zYJF4fLg16EEyeY2INsjVgwUYSKHEND1lF6L-Habex7SVtCGr2JQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQBPkuzxvvP86J_8vtcyXytK0RIDIRLqyB_GVWEa9FRqi7p5UKEbvljQo45-owOOiVI8FFaoKkRFsBPQxcMnEKOuiB1DnLu1L6Ky4AYNeDC0PUoKn1Z_lOS1qYIt93Xyc7XEASHQ6ttRs5VwnuKayGU9CUkVmIaNbxUcEBw7ol9vxHRjGJl3XIxCBy0te7zr6XZiddpaU3RlkzIc44yVxopXAxrkNMBVBD3K6sG3C7iFuaL3BBd9tqs4JaTXGOiqkCjsS-WwNTLBVY2KDsIFeLIhIBxBLaVC4te50conBKx45sU-cxl-p4tiB5tWUpcsj35OAa_5vKYdb17HGXBiP92h9sPg3wgMonBgZFo9PyUcOk-GMcefnNdoH1zYJF4fLg16EEyeY2INsjVgwUYSKHEND1lF6L-Habex7SVtCGr2JQ
INFO:app.my_middleware:Facebook callback received with code: AQBPkuzxvvP86J_8vtcyXytK0RIDIRLqyB_GVWEa9FRqi7p5UKEbvljQo45-owOOiVI8FFaoKkRFsBPQxcMnEKOuiB1DnLu1L6Ky4AYNeDC0PUoKn1Z_lOS1qYIt93Xyc7XEASHQ6ttRs5VwnuKayGU9CUkVmIaNbxUcEBw7ol9vxHRjGJl3XIxCBy0te7zr6XZiddpaU3RlkzIc44yVxopXAxrkNMBVBD3K6sG3C7iFuaL3BBd9tqs4JaTXGOiqkCjsS-WwNTLBVY2KDsIFeLIhIBxBLaVC4te50conBKx45sU-cxl-p4tiB5tWUpcsj35OAa_5vKYdb17HGXBiP92h9sPg3wgMonBgZFo9PyUcOk-GMcefnNdoH1zYJF4fLg16EEyeY2INsjVgwUYSKHEND1lF6L-Habex7SVtCGr2JQ
INFO:app.my_middleware:Facebook callback received with code: AQBPkuzxvvP86J_8vtcyXytK0RIDIRLqyB_GVWEa9FRqi7p5UKEbvljQo45-owOOiVI8FFaoKkRFsBPQxcMnEKOuiB1DnLu1L6Ky4AYNeDC0PUoKn1Z_lOS1qYIt93Xyc7XEASHQ6ttRs5VwnuKayGU9CUkVmIaNbxUcEBw7ol9vxHRjGJl3XIxCBy0te7zr6XZiddpaU3RlkzIc44yVxopXAxrkNMBVBD3K6sG3C7iFuaL3BBd9tqs4JaTXGOiqkCjsS-WwNTLBVY2KDsIFeLIhIBxBLaVC4te50conBKx45sU-cxl-p4tiB5tWUpcsj35OAa_5vKYdb17HGXBiP92h9sPg3wgMonBgZFo9PyUcOk-GMcefnNdoH1zYJF4fLg16EEyeY2INsjVgwUYSKHEND1lF6L-Habex7SVtCGr2JQ
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQBPkuzxvvP86J_8vtcyXytK0RIDIRLqyB_GVWEa9FRqi7p5UKEbvljQo45-owOOiVI8FFaoKkRFsBPQxcMnEKOuiB1DnLu1L6Ky4AYNeDC0PUoKn1Z_lOS1qYIt93Xyc7XEASHQ6ttRs5VwnuKayGU9CUkVmIaNbxUcEBw7ol9vxHRjGJl3XIxCBy0te7zr6XZiddpaU3RlkzIc44yVxopXAxrkNMBVBD3K6sG3C7iFuaL3BBd9tqs4JaTXGOiqkCjsS-WwNTLBVY2KDsIFeLIhIBxBLaVC4te50conBKx45sU-cxl-p4tiB5tWUpcsj35OAa_5vKYdb17HGXBiP92h9sPg3wgMonBgZFo9PyUcOk-GMcefnNdoH1zYJF4fLg16EEyeY2INsjVgwUYSKHEND1lF6L-Habex7SVtCGr2JQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQBPkuzxvvP86J_8vtcyXytK0RIDIRLqyB_GVWEa9FRqi7p5UKEbvljQo45-owOOiVI8FFaoKkRFsBPQxcMnEKOuiB1DnLu1L6Ky4AYNeDC0PUoKn1Z_lOS1qYIt93Xyc7XEASHQ6ttRs5VwnuKayGU9CUkVmIaNbxUcEBw7ol9vxHRjGJl3XIxCBy0te7zr6XZiddpaU3RlkzIc44yVxopXAxrkNMBVBD3K6sG3C7iFuaL3BBd9tqs4JaTXGOiqkCjsS-WwNTLBVY2KDsIFeLIhIBxBLaVC4te50conBKx45sU-cxl-p4tiB5tWUpcsj35OAa_5vKYdb17HGXBiP92h9sPg3wgMonBgZFo9PyUcOk-GMcefnNdoH1zYJF4fLg16EEyeY2INsjVgwUYSKHEND1lF6L-Habex7SVtCGr2JQ
INFO:app.my_middleware:Facebook callback received with code: AQBPkuzxvvP86J_8vtcyXytK0RIDIRLqyB_GVWEa9FRqi7p5UKEbvljQo45-owOOiVI8FFaoKkRFsBPQxcMnEKOuiB1DnLu1L6Ky4AYNeDC0PUoKn1Z_lOS1qYIt93Xyc7XEASHQ6ttRs5VwnuKayGU9CUkVmIaNbxUcEBw7ol9vxHRjGJl3XIxCBy0te7zr6XZiddpaU3RlkzIc44yVxopXAxrkNMBVBD3K6sG3C7iFuaL3BBd9tqs4JaTXGOiqkCjsS-WwNTLBVY2KDsIFeLIhIBxBLaVC4te50conBKx45sU-cxl-p4tiB5tWUpcsj35OAa_5vKYdb17HGXBiP92h9sPg3wgMonBgZFo9PyUcOk-GMcefnNdoH1zYJF4fLg16EEyeY2INsjVgwUYSKHEND1lF6L-Habex7SVtCGr2JQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQBPkuzxvvP86J_8vtcyXytK0RIDIRLqyB_GVWEa9FRqi7p5UKEbvljQo45-owOOiVI8FFaoKkRFsBPQxcMnEKOuiB1DnLu1L6Ky4AYNeDC0PUoKn1Z_lOS1qYIt93Xyc7XEASHQ6ttRs5VwnuKayGU9CUkVmIaNbxUcEBw7ol9vxHRjGJl3XIxCBy0te7zr6XZiddpaU3RlkzIc44yVxopXAxrkNMBVBD3K6sG3C7iFuaL3BBd9tqs4JaTXGOiqkCjsS-WwNTLBVY2KDsIFeLIhIBxBLaVC4te50conBKx45sU-cxl-p4tiB5tWUpcsj35OAa_5vKYdb17HGXBiP92h9sPg3wgMonBgZFo9PyUcOk-GMcefnNdoH1zYJF4fLg16EEyeY2INsjVgwUYSKHEND1lF6L-Habex7SVtCGr2JQ
INFO:app.my_middleware:Facebook callback received with code: AQBPkuzxvvP86J_8vtcyXytK0RIDIRLqyB_GVWEa9FRqi7p5UKEbvljQo45-owOOiVI8FFaoKkRFsBPQxcMnEKOuiB1DnLu1L6Ky4AYNeDC0PUoKn1Z_lOS1qYIt93Xyc7XEASHQ6ttRs5VwnuKayGU9CUkVmIaNbxUcEBw7ol9vxHRjGJl3XIxCBy0te7zr6XZiddpaU3RlkzIc44yVxopXAxrkNMBVBD3K6sG3C7iFuaL3BBd9tqs4JaTXGOiqkCjsS-WwNTLBVY2KDsIFeLIhIBxBLaVC4te50conBKx45sU-cxl-p4tiB5tWUpcsj35OAa_5vKYdb17HGXBiP92h9sPg3wgMonBgZFo9PyUcOk-GMcefnNdoH1zYJF4fLg16EEyeY2INsjVgwUYSKHEND1lF6L-Habex7SVtCGr2JQ
INFO:app.my_middleware:Facebook callback received with code: AQBPkuzxvvP86J_8vtcyXytK0RIDIRLqyB_GVWEa9FRqi7p5UKEbvljQo45-owOOiVI8FFaoKkRFsBPQxcMnEKOuiB1DnLu1L6Ky4AYNeDC0PUoKn1Z_lOS1qYIt93Xyc7XEASHQ6ttRs5VwnuKayGU9CUkVmIaNbxUcEBw7ol9vxHRjGJl3XIxCBy0te7zr6XZiddpaU3RlkzIc44yVxopXAxrkNMBVBD3K6sG3C7iFuaL3BBd9tqs4JaTXGOiqkCjsS-WwNTLBVY2KDsIFeLIhIBxBLaVC4te50conBKx45sU-cxl-p4tiB5tWUpcsj35OAa_5vKYdb17HGXBiP92h9sPg3wgMonBgZFo9PyUcOk-GMcefnNdoH1zYJF4fLg16EEyeY2INsjVgwUYSKHEND1lF6L-Habex7SVtCGr2JQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/client.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQBPkuzxvvP86J_8vtcyXytK0RIDIRLqyB_GVWEa9FRqi7p5UKEbvljQo45-owOOiVI8FFaoKkRFsBPQxcMnEKOuiB1DnLu1L6Ky4AYNeDC0PUoKn1Z_lOS1qYIt93Xyc7XEASHQ6ttRs5VwnuKayGU9CUkVmIaNbxUcEBw7ol9vxHRjGJl3XIxCBy0te7zr6XZiddpaU3RlkzIc44yVxopXAxrkNMBVBD3K6sG3C7iFuaL3BBd9tqs4JaTXGOiqkCjsS-WwNTLBVY2KDsIFeLIhIBxBLaVC4te50conBKx45sU-cxl-p4tiB5tWUpcsj35OAa_5vKYdb17HGXBiP92h9sPg3wgMonBgZFo9PyUcOk-GMcefnNdoH1zYJF4fLg16EEyeY2INsjVgwUYSKHEND1lF6L-Habex7SVtCGr2JQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/client.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQBPkuzxvvP86J_8vtcyXytK0RIDIRLqyB_GVWEa9FRqi7p5UKEbvljQo45-owOOiVI8FFaoKkRFsBPQxcMnEKOuiB1DnLu1L6Ky4AYNeDC0PUoKn1Z_lOS1qYIt93Xyc7XEASHQ6ttRs5VwnuKayGU9CUkVmIaNbxUcEBw7ol9vxHRjGJl3XIxCBy0te7zr6XZiddpaU3RlkzIc44yVxopXAxrkNMBVBD3K6sG3C7iFuaL3BBd9tqs4JaTXGOiqkCjsS-WwNTLBVY2KDsIFeLIhIBxBLaVC4te50conBKx45sU-cxl-p4tiB5tWUpcsj35OAa_5vKYdb17HGXBiP92h9sPg3wgMonBgZFo9PyUcOk-GMcefnNdoH1zYJF4fLg16EEyeY2INsjVgwUYSKHEND1lF6L-Habex7SVtCGr2JQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/client.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/client.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQBPkuzxvvP86J_8vtcyXytK0RIDIRLqyB_GVWEa9FRqi7p5UKEbvljQo45-owOOiVI8FFaoKkRFsBPQxcMnEKOuiB1DnLu1L6Ky4AYNeDC0PUoKn1Z_lOS1qYIt93Xyc7XEASHQ6ttRs5VwnuKayGU9CUkVmIaNbxUcEBw7ol9vxHRjGJl3XIxCBy0te7zr6XZiddpaU3RlkzIc44yVxopXAxrkNMBVBD3K6sG3C7iFuaL3BBd9tqs4JaTXGOiqkCjsS-WwNTLBVY2KDsIFeLIhIBxBLaVC4te50conBKx45sU-cxl-p4tiB5tWUpcsj35OAa_5vKYdb17HGXBiP92h9sPg3wgMonBgZFo9PyUcOk-GMcefnNdoH1zYJF4fLg16EEyeY2INsjVgwUYSKHEND1lF6L-Habex7SVtCGr2JQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/client.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQBPkuzxvvP86J_8vtcyXytK0RIDIRLqyB_GVWEa9FRqi7p5UKEbvljQo45-owOOiVI8FFaoKkRFsBPQxcMnEKOuiB1DnLu1L6Ky4AYNeDC0PUoKn1Z_lOS1qYIt93Xyc7XEASHQ6ttRs5VwnuKayGU9CUkVmIaNbxUcEBw7ol9vxHRjGJl3XIxCBy0te7zr6XZiddpaU3RlkzIc44yVxopXAxrkNMBVBD3K6sG3C7iFuaL3BBd9tqs4JaTXGOiqkCjsS-WwNTLBVY2KDsIFeLIhIBxBLaVC4te50conBKx45sU-cxl-p4tiB5tWUpcsj35OAa_5vKYdb17HGXBiP92h9sPg3wgMonBgZFo9PyUcOk-GMcefnNdoH1zYJF4fLg16EEyeY2INsjVgwUYSKHEND1lF6L-Habex7SVtCGr2JQ
INFO:app.my_middleware:Facebook callback received with code: AQBPkuzxvvP86J_8vtcyXytK0RIDIRLqyB_GVWEa9FRqi7p5UKEbvljQo45-owOOiVI8FFaoKkRFsBPQxcMnEKOuiB1DnLu1L6Ky4AYNeDC0PUoKn1Z_lOS1qYIt93Xyc7XEASHQ6ttRs5VwnuKayGU9CUkVmIaNbxUcEBw7ol9vxHRjGJl3XIxCBy0te7zr6XZiddpaU3RlkzIc44yVxopXAxrkNMBVBD3K6sG3C7iFuaL3BBd9tqs4JaTXGOiqkCjsS-WwNTLBVY2KDsIFeLIhIBxBLaVC4te50conBKx45sU-cxl-p4tiB5tWUpcsj35OAa_5vKYdb17HGXBiP92h9sPg3wgMonBgZFo9PyUcOk-GMcefnNdoH1zYJF4fLg16EEyeY2INsjVgwUYSKHEND1lF6L-Habex7SVtCGr2JQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/client.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQBPkuzxvvP86J_8vtcyXytK0RIDIRLqyB_GVWEa9FRqi7p5UKEbvljQo45-owOOiVI8FFaoKkRFsBPQxcMnEKOuiB1DnLu1L6Ky4AYNeDC0PUoKn1Z_lOS1qYIt93Xyc7XEASHQ6ttRs5VwnuKayGU9CUkVmIaNbxUcEBw7ol9vxHRjGJl3XIxCBy0te7zr6XZiddpaU3RlkzIc44yVxopXAxrkNMBVBD3K6sG3C7iFuaL3BBd9tqs4JaTXGOiqkCjsS-WwNTLBVY2KDsIFeLIhIBxBLaVC4te50conBKx45sU-cxl-p4tiB5tWUpcsj35OAa_5vKYdb17HGXBiP92h9sPg3wgMonBgZFo9PyUcOk-GMcefnNdoH1zYJF4fLg16EEyeY2INsjVgwUYSKHEND1lF6L-Habex7SVtCGr2JQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/client.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQBPkuzxvvP86J_8vtcyXytK0RIDIRLqyB_GVWEa9FRqi7p5UKEbvljQo45-owOOiVI8FFaoKkRFsBPQxcMnEKOuiB1DnLu1L6Ky4AYNeDC0PUoKn1Z_lOS1qYIt93Xyc7XEASHQ6ttRs5VwnuKayGU9CUkVmIaNbxUcEBw7ol9vxHRjGJl3XIxCBy0te7zr6XZiddpaU3RlkzIc44yVxopXAxrkNMBVBD3K6sG3C7iFuaL3BBd9tqs4JaTXGOiqkCjsS-WwNTLBVY2KDsIFeLIhIBxBLaVC4te50conBKx45sU-cxl-p4tiB5tWUpcsj35OAa_5vKYdb17HGXBiP92h9sPg3wgMonBgZFo9PyUcOk-GMcefnNdoH1zYJF4fLg16EEyeY2INsjVgwUYSKHEND1lF6L-Habex7SVtCGr2JQ
INFO:root:Current server time: 2024-05-11 14:56:50.368508
INFO:app.my_middleware:Facebook callback received with code: AQDckpMOuAwl1ygx999ZjfY5Jd3wpJLFMqpBg0lncDQvqg1AMiQ-Kw2E4u1YSNCjTmmgAALWYgM6-3-75rCoxWXn0k_AXlu8b0a_nwQQvn5FUkoD2QP3alMhCC_RTIBZipBak87JcKJuoWR06YN-Ayg229rjtZDFaFgtB6xw0xE8Duzw9pfyNC_Ae2NM4dJ6duxPSpN-0DX1Y0NzJgpwqyi2ukZrZqA4LMNUjrStOlY5xL39V-9RWRNsV8jJhpKPLSFadhR17B0cY1POK6yyTmPRbtUHwAmCnMh1Ji3CDO2PoTdnj4yjVh-s1U29nCAfcFP__MKYiALItCD_NPhQXFWqNPGzFtuuSwpjjkKugAiFIyncbbPffZxYv7LqMtqS7GOGdXZmEfBnZkqoHgkS7IHjvFB0AqmaFpNnnlgzc0BQPQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/client.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQBjtGWy3jDmE-2hdjPATqA3B8rdb_9X5bfOMleRnHm13vHx5yQbeG3qVLyfB0p015TFQ1_YoOeKW5z97kWtAoj7ZIZcEgvIrdzerwmU-PNATUZgulTks_4e1cpe97OBHc5TsBf5LbTjOA7SbBDAGu5R_4dc1oL-mZg35m4XQc2d2TQDbJR6VK3-mHwshKQ6XRXjFdBCYkTYZLPjimvqu737kU8mI-SRvonv06172-da2i5xrLNSEpQGkcqf33bcX3aFj_D-i5v4OqPtFldNhVYP-TN5Bl0iebAOLU1btZK5SAR85JE1bbvM1ded6tAn-F2A_RsBmtMM-dcAXNJ3Qmtd39AB5GaCYKSw7daFTsJgc0n2USTA67p4awgJwX95sFtlrLx6egojmou9AST_ocgDDawPFIxe_tlfqJAlUV3K8g
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/client.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQDdm3shH8V2D_Yqoh4f9-OBq_vJspmfooyNkis37CZ0qSm3avz57asa_2iNVjrwX4bLXiAzfvTlDTA8Rpv94E0-C8-aOOmMl5fMBwHiC0BQSWJhG84OCvENnB6aw8M-tM422TkoUvmK0TOUbEjuNhvPStGjE620fR_B6JyYJBrIGlEMkw8fuYZ-SUVpHb4jv0UfmRtfhXt46pfjuDn9SGAKEe2tFZVkSJoKpfqNlO4wFZu7l-Nqjk9VbyxYXmD9lBGzH8ANYhAOZ-IwVmo5G0Uu0daGkUwkUpdsPAx9d3tRhktc5UIdcafaJE6dR4eP9ejmTCu1L_jbXbB6LgmsS_mBWbVPWlmDWq5tcL8LhR0DmSiRpq6GMkN-TKJD6XpaqH5mKtTeDjyOsURWjsBYIhyMISa9Y735U10EifhMQa8Wfg
ERROR:django.request:Internal Server Error: /accounts/facebook/login/callback/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 149, in dispatch
    access_token = self.adapter.get_access_token_data(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 72, in get_access_token_data
    data = client.get_access_token(code, pkce_code_verifier=pkce_code_verifier)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/client.py", line 78, in get_access_token
    'client_id', data.client_id
                 ^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'client_id'
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/client.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQCGt44ahlfYTyhqa3azpFnz6yC1ueJHh2kPXUpipTI1TnhiGyxeXFLVGm8aOxrJiwEOyZED8O08_YfMPyxN1MkupxRWHcG8r7uLxaS2fmBV88GDZwDd8xIsDHy9jVsu7AIbp6XiUgdBenLZcG6KGr6HZJLfPYMgzu5y47e1d9i7lLB_3dTuAGZ8ppaNbmrhwgK8X37M3vT4A3plvtZZk29Ut3wEzZBC-u6G7NSOwykrk9vIEegjgAk1BBjA7grpdNqXhDKrP5qRC44ia6D1RUI0MP0Yrgh5gJ2AQ9P5VgAvfUe_xxQOJcor10l-V8wmfO-S5-QqHLidmgwbPTVKNGOPGkueDAiuLl0RXcsb6bqK8XTWgZE4FcXWlo5BAPyBMs_-oG2tIFCK2zPDPcJknTD6OuvTebkprUfFWsY_xa6GeA
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/client.py changed, reloading.
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/client.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQCdXjtJeXTu4fytqoHzd5NG1jWJ1GYEayCchZBjgBNP9iUx5qaDRiUyaCp1dHLCZ-sBvb50IcSvfbhmNaYYRs7agL8m8Xix5DiU6UiTjCV-OFVdF4eUlnukuRI7YeroU7LFiq-d2XNPuyxO9NAb3p0ZO4F3lRoqufx4OmmUkPTR5aQY4Z1Q6vJfEdDggMFZELlC2Kr2OXvbSIW-9uvE1qlKnwu-y0F76WxUzQKiy2ZRDfzM5g6qPbdojQVzi4DE5xXvwY1HnYHsny9VZD95ag5oe5Bznzs2U7y9ewbKFU7W4edY88NpmszrpBus6YFKUN5YJs9mQVOhaL4J1Boo0avkNUy9rakwXGH5SbR_XsVm_wYvVR268TWmF6MVI6QrJQgKooyLP50D60B4xzEQ59KwUloyudDNAzjVpSZoK65dnQ
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/client.py changed, reloading.
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/client.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQAfrK7g9UMjtcfDKFBD89LFXuq_1DW_XlKVdDPZxPdx8XdNd0nV1WXT4fSQfCnycvtqhztNnqYKMeofgFMSY7g74JKCkdYRf6b7_AKk2ebkS2jWtcedV0kyJsyrRSCKKgLOQJIlnVQ_vjlcaPP9Cg_YXQo45m8qhMf4f9aYLQQyRcqhGLuzkEbey5c1FBRVpRWiQJGzuaijnvuuEXVGbqKzOmeADq1dJKSFigd_cjfzcFLc9iBbn41_IF1xcdkxAPsnC3_QlX_LYPrg3TGdMmQo3PNBM67WNjG6nJwmsUv5XadeelaZ-C2VvdfyknozxJwRad9tiJ1Md9M7pcLAfVZ3N-GRoYnpEesRsOXH5f3xZl9_mfTyP-MZ5XbRlhfGUPqG21TBdAxRp5sP8gbnxRHqOZ-g1NYJSXfpgN8L9vFVRA
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/client.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQAmBj7fenN_wn9UEEKxO9Gz561xazfJ8XTYopi7sy5Bt63YeUV9tscXKl_ZqKq_Ga-fBxVBIYk_WXq7gMLEW4VLkvHY9hwCZ8Z5GQiF8lUAa1O-mkBdDfdz6HA89pihUXj1yFJJD8rEVCwOAYadI8j6wPkFLg7GVnsVb78kdVTTjbshIzeW5iP4ynyRCfl9ks4sHBCDc4AwEtj9gp7QZsiSqrE0iUFsav_VMD8EnH9iprHZi8QZ9VUgz99HIgvCGXpudE-U33fnR8rLtc2-xn8yfyOdGRep8hDR6XjXXTlhcdzBh9jrGdwZxHNiQSoP6oqGiky6UKeCvSJ7vNpjKO9SOo35v5qGswqFuW-0r2a5pHAXbZoqhKH-exKC8hAyqPG2SQosf6iKnvjmt3B6Yn4wZj7YTRoj11Dek_N7QsZ6ag
ERROR:django.request:Internal Server Error: /accounts/facebook/login/callback/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 160, in dispatch
    return complete_social_login(request, login)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/helpers.py", line 51, in complete_social_login
    return flows.login.complete_login(request, sociallogin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/internal/flows/login.py", line 39, in complete_login
    process = sociallogin.state.get("process")
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/client.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQAU_0n3DR_PaFO3UhIYxqdc1eGosp7oUcxJOU-JnyzW6gLc6L_H0n3R1qvCUQPwJ1DAqcrgbR4Rf6CZly3blDn4wG9QoNEHAIIvoephviV48nBVOmi7-i5WdtHR2bbrmJxlXQuXsjlcMlMB6R2znLzPHJPVE5p6oinEdB1JCA5dvXaIiG4_NoMMURNGjHRQcjN8BL5ebvG__zAe-u9ski5AQ5iW2uzVGIq7kC8pyOAGtR6CCrDEa-cbOCXGJ4faScLZxuNYKawhNjjOg-F4ensjwiQsJPhR_oBjkaGFoRTT3FH9tCmMbir055hos_FLQ1qcTiKrQUZtZAyuMGLM8h90unmYx5t4wFPUhTr8JPz4MWv0eaeHwDnsO7GXD8gKsIUTMDegAK7G8oqpi0mQBk9_DBccuJyp5eDE1deHTRGpSw
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/client.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQB3dRy-o39xevPszTuVqj0fdAj_hLmkLNYEBDyKIMvflUkiEjMc4EhNdN7WuTonLRMQEG6W8mZFYrfWZ0Whfw_fgNXkae6W5X877_RUXHgNEKxe0ljeW-oyLVpW6P29PzMCxlutzqRz0sxyd4QDYQLGBXn5oGNucc5K4wUF6sZ1Qwx0fYgv4gF_sF_g9bFHfJOlQhpb0o9QZ9ZOdQcICX9CvK48G1-_ubhn7lRTEzlEowUZs7X4ASw1bf3p9ISNS2dZE4YzsentmhpBEWDLZA5PDpLnB8eUdXsghh8K0OK6G1T1XPd6xwE22cYv72t7Y7jQC6fH-czxeqQOiudes7UUrZ6urLsl2YhGVkwX0Gb4hnWaj7xvJMufaN5fOberaTEzFqhNuXAzY1CzV4NBV9CoX2HAVG40YLhDIIsWedVFgQ
ERROR:django.request:Internal Server Error: /accounts/facebook/login/callback/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 160, in dispatch
    return complete_social_login(request, login)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/helpers.py", line 51, in complete_social_login
    return flows.login.complete_login(request, sociallogin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/internal/flows/login.py", line 39, in complete_login
    process = sociallogin.state.get("process")
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/client.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQCTa1T_870JDOOsSqJED-yVSPPRbutA7aBNffHTa9kUJ6XRF3bjjYLo2KypEdIJ_ziBWK3ALu5pBvcN4TR20NjcX7u9jKCzXYqciKPi52ZN5O4zkcwXuYj_R_O4KzFiMGHf6bOI-eY4rHqMarKv12B3Du2x3MnlJDGf-g66os96vM9w3WD-KpIyB5pwEpS_2p_XP3NI4GLOAVs4JN5m1x9g0c0yHYZvTg82ZK1IK5KawUI7WW4u8_xvW4M-WHozGlBL_HG5clB7lybfN-qwcvMHFYIOrzeX0TzBUqf2LJsKzW5VbEbuEDlObA3VEXKLNEj0Ntd4ueqi3dHdIG8FeLgNclm5lbCTxbe3CLl7YOIECjLh2zJTfVmbdTOPPD3zim07PpfmtNa2qS6hb5llgAR2v0ocXF8WhaBCcIFzPArwJw
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQCTa1T_870JDOOsSqJED-yVSPPRbutA7aBNffHTa9kUJ6XRF3bjjYLo2KypEdIJ_ziBWK3ALu5pBvcN4TR20NjcX7u9jKCzXYqciKPi52ZN5O4zkcwXuYj_R_O4KzFiMGHf6bOI-eY4rHqMarKv12B3Du2x3MnlJDGf-g66os96vM9w3WD-KpIyB5pwEpS_2p_XP3NI4GLOAVs4JN5m1x9g0c0yHYZvTg82ZK1IK5KawUI7WW4u8_xvW4M-WHozGlBL_HG5clB7lybfN-qwcvMHFYIOrzeX0TzBUqf2LJsKzW5VbEbuEDlObA3VEXKLNEj0Ntd4ueqi3dHdIG8FeLgNclm5lbCTxbe3CLl7YOIECjLh2zJTfVmbdTOPPD3zim07PpfmtNa2qS6hb5llgAR2v0ocXF8WhaBCcIFzPArwJw
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/client.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/utils.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/utils.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/utils.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/utils.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/utils.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/utils.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/utils.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/utils.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/http/request.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/http/request.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/http/request.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/http/request.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/http/request.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/http/request.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/http/request.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/http/request.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQC_ogYQiVK5isZ4UwkOEWXGzCygcI3QbxQ52XLS7PaWkMErnUJQK0FyJXwqBN5b56PC6QOr7noCpJ8FmDWS-M6pP5m3qN3Ve0Ur-iUen6abKAv4aHUfROrWeogcOHm_nbQXtohh82H5rOp05u1yQWQ-W_k7PB1nZmntJQ76vEYmHWZo_KfmIGX92PRq8i9s37AkUKr7OQwMdsW1sC7hCPzdSsQR7PQ2bT6lBRSntdC1DS48rXP6gzDCFdie1u2luphbWG-WP55gct9yIGRXEXLHWZqJKfqUtpJo2aL8O7MB831f9QOd0ePgZ8rLMmnXaJ5BX84YILi2MvUgzvWhDhkE5-2zd1XajTi126i2X5Go0eSsyYhU50SyH5zTlco737MCg7zVoRbeDeDLtyj4sJdeJXZjhVCJ5KIFf3RT1vHd3A
INFO:app.my_middleware:Facebook callback received with code: AQBtlPYUye0pB5hXNiCSk6eqtmsb06VL1i_vVuAvprn-TvE9JgOt-0uBxpHtxy_2R3TpkF5Xlr6G8osHxGjoCHxhj_qAqA__6xEwOEahamhQqsa4JOGvGrkLJ2NFsz-iAbGlLMQ9ncvCB4uxf_G5izoYFDrZsd3358FAMbiGzyqAyff8vzhgQ8mdgeT5u2w8ERC6ZXMusGkNPXzg1EIl7LOfbYUZr1ZEAzKEMKjsaTD9eYlQvdfIrwJPMitOkJDTD-Cp5fX8WlF92ngAaYniZ8uxgfqDHB0BVSbGrBFAfFkLNP8BPF4h-ppPYFAud64HXNw78OFtqUJksZZ_Ek0_yt90_Gjy1QTE7NQ6uh4pEo-i8JNLTEWOtyWYXQq0YHSCk-RnFMNX3SPcdZzjm3YK_3E4kCzhcGMAXX8ODrXZKz08rg
ERROR:django.request:Internal Server Error: /accounts/facebook/login/callback/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 160, in dispatch
    return complete_social_login(request, login)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/helpers.py", line 51, in complete_social_login
    return flows.login.complete_login(request, sociallogin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/internal/flows/login.py", line 39, in complete_login
    process = sociallogin.state.get("process")
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQBtlPYUye0pB5hXNiCSk6eqtmsb06VL1i_vVuAvprn-TvE9JgOt-0uBxpHtxy_2R3TpkF5Xlr6G8osHxGjoCHxhj_qAqA__6xEwOEahamhQqsa4JOGvGrkLJ2NFsz-iAbGlLMQ9ncvCB4uxf_G5izoYFDrZsd3358FAMbiGzyqAyff8vzhgQ8mdgeT5u2w8ERC6ZXMusGkNPXzg1EIl7LOfbYUZr1ZEAzKEMKjsaTD9eYlQvdfIrwJPMitOkJDTD-Cp5fX8WlF92ngAaYniZ8uxgfqDHB0BVSbGrBFAfFkLNP8BPF4h-ppPYFAud64HXNw78OFtqUJksZZ_Ek0_yt90_Gjy1QTE7NQ6uh4pEo-i8JNLTEWOtyWYXQq0YHSCk-RnFMNX3SPcdZzjm3YK_3E4kCzhcGMAXX8ODrXZKz08rg
INFO:app.my_middleware:Facebook callback received with code: AQBtlPYUye0pB5hXNiCSk6eqtmsb06VL1i_vVuAvprn-TvE9JgOt-0uBxpHtxy_2R3TpkF5Xlr6G8osHxGjoCHxhj_qAqA__6xEwOEahamhQqsa4JOGvGrkLJ2NFsz-iAbGlLMQ9ncvCB4uxf_G5izoYFDrZsd3358FAMbiGzyqAyff8vzhgQ8mdgeT5u2w8ERC6ZXMusGkNPXzg1EIl7LOfbYUZr1ZEAzKEMKjsaTD9eYlQvdfIrwJPMitOkJDTD-Cp5fX8WlF92ngAaYniZ8uxgfqDHB0BVSbGrBFAfFkLNP8BPF4h-ppPYFAud64HXNw78OFtqUJksZZ_Ek0_yt90_Gjy1QTE7NQ6uh4pEo-i8JNLTEWOtyWYXQq0YHSCk-RnFMNX3SPcdZzjm3YK_3E4kCzhcGMAXX8ODrXZKz08rg
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQAOY0SFoOnfcaU8AqjrrvoBw8HMMJIBfNz9WUjiKr8SxKjauSfW90LreUIgS_x9MUYKFnuIh3S-FFCeNy7xxPO6RDdN0GNa7d0y81yvQofn2ekFsmJHLJ2mn1X6W8SnsyL7eSHplnsmFe3BMwqXy0qn2mCj7EODnI1_UAFTkgFBNd0D6U1uzhGjsIctOPQ_xLtHRgDX1ZgURBT63yBc9YkB5zsbB4rTvJV-s0E1OAJwODgd6ImFGtffUbd5buoXVNtlzVe9l4zWF9dJnKstq-mRSYEM92ZmKs6o9Gk6aRjgN8XHv8P1jYrukbYukwU33GmbtGVsneBSuuuRiDOS4_4FOHYd6umgaKdGrcMqGaewFEie01ymKBrx3e9SEqq6baxN5yVn7akUbF9yvc4SWMU_zXrhsoKf8feXO-Odk9R6vA
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQAOY0SFoOnfcaU8AqjrrvoBw8HMMJIBfNz9WUjiKr8SxKjauSfW90LreUIgS_x9MUYKFnuIh3S-FFCeNy7xxPO6RDdN0GNa7d0y81yvQofn2ekFsmJHLJ2mn1X6W8SnsyL7eSHplnsmFe3BMwqXy0qn2mCj7EODnI1_UAFTkgFBNd0D6U1uzhGjsIctOPQ_xLtHRgDX1ZgURBT63yBc9YkB5zsbB4rTvJV-s0E1OAJwODgd6ImFGtffUbd5buoXVNtlzVe9l4zWF9dJnKstq-mRSYEM92ZmKs6o9Gk6aRjgN8XHv8P1jYrukbYukwU33GmbtGVsneBSuuuRiDOS4_4FOHYd6umgaKdGrcMqGaewFEie01ymKBrx3e9SEqq6baxN5yVn7akUbF9yvc4SWMU_zXrhsoKf8feXO-Odk9R6vA
INFO:app.my_middleware:Facebook callback received with code: AQAOY0SFoOnfcaU8AqjrrvoBw8HMMJIBfNz9WUjiKr8SxKjauSfW90LreUIgS_x9MUYKFnuIh3S-FFCeNy7xxPO6RDdN0GNa7d0y81yvQofn2ekFsmJHLJ2mn1X6W8SnsyL7eSHplnsmFe3BMwqXy0qn2mCj7EODnI1_UAFTkgFBNd0D6U1uzhGjsIctOPQ_xLtHRgDX1ZgURBT63yBc9YkB5zsbB4rTvJV-s0E1OAJwODgd6ImFGtffUbd5buoXVNtlzVe9l4zWF9dJnKstq-mRSYEM92ZmKs6o9Gk6aRjgN8XHv8P1jYrukbYukwU33GmbtGVsneBSuuuRiDOS4_4FOHYd6umgaKdGrcMqGaewFEie01ymKBrx3e9SEqq6baxN5yVn7akUbF9yvc4SWMU_zXrhsoKf8feXO-Odk9R6vA
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQAOY0SFoOnfcaU8AqjrrvoBw8HMMJIBfNz9WUjiKr8SxKjauSfW90LreUIgS_x9MUYKFnuIh3S-FFCeNy7xxPO6RDdN0GNa7d0y81yvQofn2ekFsmJHLJ2mn1X6W8SnsyL7eSHplnsmFe3BMwqXy0qn2mCj7EODnI1_UAFTkgFBNd0D6U1uzhGjsIctOPQ_xLtHRgDX1ZgURBT63yBc9YkB5zsbB4rTvJV-s0E1OAJwODgd6ImFGtffUbd5buoXVNtlzVe9l4zWF9dJnKstq-mRSYEM92ZmKs6o9Gk6aRjgN8XHv8P1jYrukbYukwU33GmbtGVsneBSuuuRiDOS4_4FOHYd6umgaKdGrcMqGaewFEie01ymKBrx3e9SEqq6baxN5yVn7akUbF9yvc4SWMU_zXrhsoKf8feXO-Odk9R6vA
INFO:app.my_middleware:Facebook callback received with code: AQASYon4S0bvk1jelSInj-V9GJ6jxNPllu4HVh8ZAWkcczpVUKi76vjRtJjNYNZch8lf-pH46K5pFRZV-uKW6VTje5ZmvZeyba3fjGj4Nsb2xUtEdXpvIx7xsJbc6cX0cKCDQBtOsiAB5U2ZMEyx5Nn54NN4dA6H6Prk2xVk6yE9_2gUkkBVXGq7Rd1wK-tvIz_GHsP5s-W2iN_2IEGmt9le9hwwZvvD4t5YXY1wxFcafz9L0c6gAZvHmTr4joESYt3dnr4x4-Ch2N1SIO2yFC_1gH8apMrf4Hg0B36681nUmBrvSL6FaRB5xzsAplr7pJ1xCcMi5_2ZVXUM0g32nkFXiFYmHXDs1es4I6qzswPxJfc8CfD_2RL0OSEadTkQ5hBFtwDeDUNnFpFMN5wWcxRFC27O9ijRmRxzEbGMH0b1Nw
INFO:root:Current server time: 2024-05-11 15:35:43.037230
INFO:app.my_middleware:Facebook callback received with code: AQCKzp6Wvn8mug3FjRuEpeXWyUbjge_Y2DZxG8AK--QiFyrT4OACDUSI-p-mXa5cjEuxs0l0dMXAaX8PHad-m8veuUrH9r_AiaMpBJfOGcTZjP_8Hgn5UnUl8S0ZDG3ROXdeY0XSwpWr_6CmcUMf3_-E0k6a-t1AD4UuweThOVMEDISZNpXx6Uh28LKnoEhtP8e1UPtOXJFAtxevyO_kkvolDCIC_mhw_6d9iPfMp9eN3H0RPsG0FwcRBjXrj3zzBTVxQdGTyRtKQ61TLqcdWecCub5sWX1gmOfiMoWz3ptOdrcWkXMpbGJRIOVnNA_IBS2RGDCypCEC52GmTyYCftfEuSQ5a5BrhUYQwop-FrtEsaFR-peWHYf35eEJ8XYEB516v79lyU0VQdsUWURptWubQhqPhvgls6X6sWadQBVU3w
ERROR:django.request:Internal Server Error: /accounts/facebook/login/callback/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 147, in dispatch
    app = provider.app
          ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'app'
INFO:django.utils.autoreload:/Users/huy/code/project/.venv/lib/python3.12/site-packages/allauth/socialaccount/providers/oauth2/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:app.my_middleware:Facebook callback received with code: AQAkE0UbCn1YVKxKViJifD0bi4kn6WDU1ACztE1sWvIHF9DT_noYXYvQtulTbVVJfHQvuwtuo4C9xtIskISL2a82kn3VDrYQ-Vn4snsfbjzQMYUHRCwAv38r_RICJ7UqOKtJnlWo_5VkXH9fWqwYbO7r5XDsDbZyVRyVdFnhGDFsvmZSKHmm_ylWCEghaOlieW-vi-KeSwtj6TC1EMeB7ibxvnIvxxIGmtEr-5x_ulFXqzH-iuRj7Tko4Q4I8p3th86uYD-scrJWP1EUj0_R1op3l33AwRjtSYnxom7qAWCfloqZsmTnSnVM1RpLEuXIFmEsqZAezPnqHSj-UNRwVqPncj81Xx8z-UdSDaIspM1ZlreK-ztj6uV7Iwb_pKMcYFePp5dAjKYfBW6wnG59Y9VtlOVgZ7d0q40xYPDChicl1A
INFO:root:Current server time: 2024-05-11 15:37:00.849472
INFO:root:Current server time: 2024-05-11 15:37:16.223961
ERROR:django.request:Internal Server Error: /api/reports/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 520, in options
    data = self.metadata_class().determine_metadata(request, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/metadata.py", line 67, in determine_metadata
    actions = self.determine_actions(request, view)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/metadata.py", line 92, in determine_actions
    serializer = view.get_serializer()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
INFO:root:Current server time: 2024-05-11 15:37:23.728169
INFO:app.my_middleware:Facebook callback received with code: AQAkMfrzWMGazluSv8NPqWHqL4RpqjcGLCzfkdJxnKZyQlvfK6VVG16-wAtKW8S_Qvf9kgE8OE_Wjpk5CZC_ItIb3dmOBeXdPIAXx0W3qBVBR0uYAdLEDuZGUNzLOlkrSnpASZi4YzacyOwEUVtsEMoRc8UWAZDQNeWy3-Zqv-38uWopysL2mveUSTsQLJ_9x0amjUHmKmq_0z769kY9BMALKKen-z13kd2ng6WCWKa0jioQebmMP_DvTSCa6_x_WcDh2s--IPfKB7s8-f-VgBZKe7DwufthIBhVZ0Pa5boHQE6WDuIiOXHtQ9mvZo5h6Taa2ubD6SJ7CjzVqPq59C7a5M9OcIWurwQu3t_g9ai9HMOuEOmRvR0Ep3N83RbQ9elyPgCA97kEz79Iy9ZSxJ0wYKSXLqv2FQU5sodz14Y5pQ
INFO:root:Current server time: 2024-05-11 15:37:31.229676
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:Current server time: 2024-05-11 15:38:37.993401
INFO:root:Current server time: 2024-05-11 15:38:39.459310
INFO:app.my_middleware:Facebook callback received with code: AQDH00IY9hIXsfozd2gSgHC9r6rY9MsLKaiNtDkpTj3QIeiVAKgPdxwCuEyILjv5Xzp6TvpA1K41LAcB6NSZElyXJXrAg86f0Nbpggiydla3oBdfo0AxfjMwBnTu2aLKl63v9FgWLQYGFVqADeDxr72oFtSMNNSMMFkhiuM2MioH86ymJfXGbhVwqJSpgmJdQ1e5nHJvPh8sHINUhIBHdWnrynLnroPSKLgqRcCLx-yMW2w9KYOSLGYP7iRdpLmqZbAvs3_vJ44Cbxn2IH_ud_XhwcoMCLT-Z0Ln4lZXrHHWcGVtgBGSXS-r9tHhtjE05f3dz5-Lyy5eK0wlk3vcIImlzKgAibcxtkWuLumrS5do6u6VoiGwoGTzSek3HUFNM5cGgVhdIHVv42tpb-62waTYfab4MlPkxtFYG5-8rpr_DA
INFO:root:Current server time: 2024-05-11 15:38:47.969105
WARNING:django.request:Not Found: /{'data': {'url': 'https://platform-lookaside.fbsbx.com/platform/profilepic/
INFO:root:Current server time: 2024-05-11 15:39:49.959783
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 481, in parse
    raise self.error(token, e)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 670, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse some characters: user.socialaccount_set.all.0.extra_data.picture| ||| user.socialaccount_set.all.0.extra_data.picture.data.url
INFO:root:Current server time: 2024-05-11 15:39:51.278482
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 481, in parse
    raise self.error(token, e)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 670, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse some characters: user.socialaccount_set.all.0.extra_data.picture| ||| user.socialaccount_set.all.0.extra_data.picture.data.url
INFO:root:Current server time: 2024-05-11 15:39:57.763187
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 481, in parse
    raise self.error(token, e)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 693, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 603, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'user'
INFO:root:Current server time: 2024-05-11 15:39:58.682905
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 481, in parse
    raise self.error(token, e)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 693, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 603, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'user'
INFO:root:Current server time: 2024-05-11 15:43:40.510132
INFO:root:Current server time: 2024-05-11 15:43:43.321797
INFO:root:Current server time: 2024-05-11 15:44:20.046676
INFO:root:Current server time: 2024-05-11 15:44:21.078897
INFO:root:Current server time: 2024-05-11 15:44:22.014134
INFO:root:Current server time: 2024-05-11 15:44:48.574809
INFO:root:Current server time: 2024-05-11 15:44:49.550639
INFO:root:Current server time: 2024-05-11 15:45:00.609141
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'ifuser.socialaccount_set.all.0.provider'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 20: 'ifuser.socialaccount_set.all.0.provider', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
INFO:root:Current server time: 2024-05-11 15:45:01.775444
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'ifuser.socialaccount_set.all.0.provider'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 20: 'ifuser.socialaccount_set.all.0.provider', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
INFO:root:Current server time: 2024-05-11 15:45:08.858174
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'ifuser.socialaccount_set.all.0.provider'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 20: 'ifuser.socialaccount_set.all.0.provider', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
INFO:root:Current server time: 2024-05-11 15:45:09.919588
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'ifuser.socialaccount_set.all.0.provider'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 20: 'ifuser.socialaccount_set.all.0.provider', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
INFO:root:Current server time: 2024-05-11 15:45:16.866218
INFO:root:Current server time: 2024-05-11 15:45:23.110032
INFO:app.my_middleware:Facebook callback received with code: AQDxChy25eod3fCaLN6ZRSuyrXj5ikFy9CpJeAj-7ny7n1K2hJ6wVtDjrgOxsa53Y9mxTfYCJahNbKFWHIWpaa1zDi81alVjRXftmXs1j3qkgK7f-xctf5nLRaOSRRdQO6NfKekpiW7Cv_GGMESw5Ztx4mRhRs39UsdUDXDkXbO3hNxG41SuCN7KppyRJPmv68JqjGgunHRWucDAW1xHdZv8IKg9RFgOe_RxPSy2YI-B9WV-G6lm_TR9DcUD4CwIktzkhq9k9oRuROJ5vhu4C08CY142UfsDbCDMpEgu6MIJASIwn81qo6EunXiVwyZLSbpBPpgd9WSXCUeKXPJkrSOpO39XNBjNfFBwL1wfiV8xbyW_SVg-D1U5RnXNU4qXaMWf677JNSOEGOwmn0I17E1YRGNY81iufC1IQQz_NutUlw
INFO:root:Current server time: 2024-05-11 15:45:33.320651
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:Current server time: 2024-05-11 15:47:36.824375
INFO:app.my_middleware:Facebook callback received with code: AQDgDLDideE5C6xeyCg05PoXdlnRGW1Q6aLUkR2qq3Pk6bqc0BnKldW14Haegy_y5WZfr3NMztxMRhVtL-sMezNkY20m6fxVJzIzLMbCl6cGXAvZ0BhIXqE17DU0fjD2IPTn74KXEUNID6vQ0O_Bx1pNS5R_EBnKTw8cScZzwce1hBXY6GEQXOqtNrDmcwrTDZJf8DY2XOL1DbVlUvo3PPD2rIsHVNjX7hUPN8LAVJTdRti-kKm8eOQZKvKpu2MbstRzms3Zxd-UBaExXX9McLc-opxuFIa7dL5qpZJt4xwT28ngyf2Qqux10qm0XwtPw37P3SamZiaJZ1yHziYJEbEpNUcQEyG6q5CTqHNFYZrr6I1lgX1cupvnEE1LX8tswdd0rKX981-zHtZaxbym3BH5YsLgymtO6Xmdrt5wkz_9hA
INFO:root:Current server time: 2024-05-11 15:47:49.684203
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:Current server time: 2024-05-11 15:48:11.094502
INFO:root:Current server time: 2024-05-11 15:48:12.183763
INFO:app.my_middleware:Facebook callback received with code: AQCw8Arl0S8iJmsGBxhpd_Fwkcjh5Q99DdD8r96CloabLFgQwbJKKk6zO38fRxoscXf-gXlHhFRsngBA9_bt87LIjvdR3hCFtmhyTx-diD-JG9UUnlelTySwJhHBqFPDeyALcijkDeH_wOSyNtSEHdxky_UXBh_h7BAlX65g_nV0-p_1MQCi73plNlyAuJv9YuSpDWANCnquxRKtiB85jR6JHxvB_SafbeZECWQCfCGwTY4OGEYQ7B1yrTaqHK_5H4x2ds5vZaOskNIFSGlI-EebWp4-AnyeFSNk-92SEQAr6BlBk5Gcv5aLBkqiq8PN34eLmxSQXQmTvCjt-57S3f_OpYIV5j2cgjr5xSRaZqrNWukpQPIyOaI4DfciC-E1qvnvajklVv-B8gM2BgmEkPEPI_x9lK1peh13LxN-j-XnLQ
INFO:root:Current server time: 2024-05-11 15:48:16.563859
INFO:root:Current server time: 2024-05-11 15:48:24.405336
INFO:root:Current server time: 2024-05-11 15:48:25.944440
INFO:app.my_middleware:Facebook callback received with code: AQAmlMa2io7szxMYmSWVnCidFN-6iwiC3J5BH0dsEe0xoyM__Uauqla0ukS2Wkfpwigu8ZUcNIcmSsq0hL-_DnNPhaqgJNxLYPuQKjyxdv4hYkpdxEkzyzq6gRdtB6QodssHQvwmXr9iH5hB8GWS10Suun48nAMvEo_5tx7TRTcDRiNhoRhIDlHvBdlLVax93PPcB26oGmeVFdfYVTBgUcH7Eb4sBXoqF0oRWggxKrRa-jmMfKoypULeHFPhzWTD7z3uTMVvtlO-pIutAera6VPEWEvV6zJuMHX8CLinNoOishjdpFVheqsOuz6ctM7xq485pU1RlOrBAcyNvJ4Fn0mOcL1sRc_RSsYpiXyaCktBTQOVLx8jYB_qft4cAtFDbTctzFNAbcWzNpP8VsV6QCacOx7kJd0eUJxGE8Jr_TYcEQ
INFO:root:Current server time: 2024-05-11 15:48:31.044396
WARNING:django.request:Not Found: /categories/
WARNING:django.request:Not Found: /categories/
WARNING:django.request:Not Found: /favicon.ico
INFO:root:Current server time: 2024-05-11 15:48:46.026137
WARNING:django.request:Not Found: /favicon.ico
INFO:app.my_middleware:Facebook callback received with code: AQCsmcVp-6D50-VOrQaVYRQCdwyq-7Jfb_G5qUSY42M_XY3H8_A4t5tb1KNb2O4gkBZWVImmTdL04iLY4DjFzDBc_Wke46Exrh-EB3TRh_u3FJVjfKuwZMm-RahPYN50vdyRu_jee33knrDnHxPGOx_MaauY3K6vNNNWW-pOcKW5y7Ku7VDmmMBkKzbpxbsncxijTEDHlTyzMHcgNU143uPhMGUnvTGPhZJ-mZbl6Ea-lzmTGa6-vMkot4tQ5WYTmAnSr-isdBAIWz5P3dRpqtNphXzTcOdb90ALgiA8SZqhg91pNmN3bq3f2tVGOcOUgqlg_LRYj-aWh5aLkEDj2N1f2Y2_xXkvAD_pizIRqiXt41gzeCk8naVtp2xVA5B8bcngE7Hm5Wz5shhf9DLmv3FnMy0snqUBPaDwIS_4SXrPEw
INFO:root:Current server time: 2024-05-11 15:48:56.474907
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:Current server time: 2024-05-11 15:49:12.952484
INFO:app.my_middleware:Facebook callback received with code: AQDY1InWAGBR57q7sHKfbW0RmouQmCsjOt4rkcuRYQHbOvK5M7LMWIcO4x68UF0ojnsqY0Zoe2GJyOZ3cqNQfpXpkyxjLwT458ftICUtlg_bZixglw4v42kx7ahx15V0qYKtYb-eiLRz-xqJ1IoqPV41Km9tEDDbgHYXqVxVK7deKrCDAC54_04-6xThnPMX2ddLmpvEjtNihjJHuR3nUs__wDZlYCOyjXypVwFvOCBDJJNVzws7Pg14F4XYrGX5fscuDmk6-O-h7Ofe0ITRxxbhmQIzrRRCRhc64-QUMo3TvWqenKH_7-wEfQosMh3iCXvJ14zg3Mku0EegVyF7mJIH37e0GHD3_cb2uPnffqeKT13JvCCUE2EZvNxmBe5W5vghicUf7ZRfW1pIzXam-UWMydgOLR8v74jRLH7bohTkuA
INFO:root:Current server time: 2024-05-11 15:49:17.858207
INFO:root:Current server time: 2024-05-11 15:49:20.150631
INFO:app.my_middleware:Facebook callback received with code: AQCuCFNwlvocnlJkbKBEnnLpzeDfcnpbTcFrrbJVdMubVyxApfanzuls4ay8I7Ez33UG7xLVVMnSRzwHVoHH6nosGzfxs_VNszlwiztiCVrI10c3Vhgz8yG-rWHlaWNsAdYOp63yVWBBMI0Wqe4b6FnBYsxyXg1kGQFNfhI_tF9YhmAW3G1QtyqRTcVhkmuBmsLziMQxGSjNQ41XkBW-rsdvA5vt5wItWxAHmtOZ7bYhLqdzRba5rFBwuGl_MXn1mEFIGfqBzVyl_1QtkxNnc_LO_wQITutvEzSYbmmzAAiivxC5xgAlxqvGivoOPY1F7ALd0qORbbSTvRFXsSUt6QHEJEz1tzXZeJWozgParoPypeOk3BN_ph4jjT8CuJU60wMOsmbdlzGaRue9FZyBEdj3TejJkCUfC2puRmV6Lb0rnw
INFO:root:Current server time: 2024-05-11 15:49:49.701240
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:Current server time: 2024-05-11 15:50:19.484311
INFO:root:Current server time: 2024-05-11 15:50:20.502066
INFO:app.my_middleware:Facebook callback received with code: AQAqhzlrJG5iFYRPJZo0VKaBcNgxg2s4X0dEZTKGFO3oemP9TluNCpJWQnmBycnH3ewORjS6uM_be262igvK6xJkJruFlhHuf9AlHcs7WlVOVHaH8w2J7aPrF4TeeHHZmg4f-I0h0OnO5T-wbMkifjF2TFPYsHffeUOtcdXi2FxjypG-2rHX5jqJDQhd7ToOqlRsfBdmT20TtY074guN6_9vu7wFaMU2tKyxrykCdedJAba4f1KpIi6skkIg7IchGbuVCZODHW6pfhdJf-AY1w7EgoRjLBeEw2yCw8NK2eWxm0w8cuNekYKVnJJ3Iblow47ujRwwPxfKtHm1lctcB90Qt_0OQhqnjyVWuE-DWR7JrblL7o6yUIlGduPzIMTodu4rjYuTLtBiVK7nOKDImGNLpkbICQ-_85V4k711rXyLZg
INFO:root:Current server time: 2024-05-11 15:50:28.470460
INFO:root:Current server time: 2024-05-11 15:50:45.223219
WARNING:django.request:Not Found: /favicon.ico
INFO:app.my_middleware:Facebook callback received with code: AQA5JfdHSAentfx3KPrT8TZ9D2rOTPkMsxfxRWYuTlZELt-I6JpMpBp8b1JzTgZGxm6XT0Tm0w02IzdPlIWlwBwI9bXweCmflDQRTDCHMEkofOgVm1ZWsWvNfmSZAoKSLHBVh5_ixofRZ-N8hDsKFuGbwxzBasFIMBmidapBefNhkkl69cfxWT6Dg6hToNr1FFd1CGf6-gBejpSmcm-m_zTF1HIXjOMEuGP5EWmQbQVjh1kXv8kfP8zfgqRVO32eEiiOWRKAlJbvP2pTTb4YyhrG7Xf6ng_0Ea_JfBzOarwf3EXI2JAeLWRCW9WoGTVRbgB_8UbbpdKu75Jbej4t6HEALdL_BxRxqNtZtsFKTGvs_Xsr_fEIoEm1d1Xpz4jd3pcYn0M76ZmGlzllvwELd8uIj2fNFLW3oRmfET0Z02Tyjw
INFO:root:Current server time: 2024-05-11 15:51:02.501321
INFO:root:Current server time: 2024-05-11 15:51:05.778619
INFO:root:Current server time: 2024-05-11 15:51:41.094406
INFO:app.my_middleware:Facebook callback received with code: AQAiQUvr-JvDP967DypCDWW2iLdZoVM_Gb7IjZnMLPXqEWL1uVI_6Lnsq6jcu39jj0jO_di4TAxPv2DSnJ0F5GvvEZ3fVP8Mx-yGWntIQY-umzRVndZrGtS_u2YvakObjhLriRm_aRdSXRbEgP33oeYl39GdP7FKmcoG4zWj96gST3oX0y08MyMWOx1fFwUDreMOT_cVvdDMXBXZnbjaBcDfYdNZj7OYx_z-zUyXi3YtA860QyaR3co81Xhri5CIddEdfjOqdQ-lf6KscXkIE9RERF7-G2j8EQogs6MgpCAA-3EfJv8SKIpKfDqqpYMvas0RfHHYjF_tEYUfdzWSZ8aV1KVEnjEHIkzC5Etooi_RoFg0wHPuJ01GK_mv9ITGd0U5xajgHpgSMv5mtNY4BGyBULq1zyG4A-Zh-xNrI7Y7Yg
INFO:root:Current server time: 2024-05-11 15:51:49.696397
INFO:root:Current server time: 2024-05-11 15:53:14.680188
INFO:root:Current server time: 2024-05-11 15:53:16.819327
INFO:app.my_middleware:Facebook callback received with code: AQBmH0L3Y3qzFPTG8Dk09wPzwoBxlJ6tpTiuCHdROCLD6aIGbJsJ8Z_D9RCtJIIyiGn6LdMhQTEgdTz4XSqHSxjJ_Tm_CXuG7q3RPgGwsEp72_9nXCmDtvWjD4LZaze1D0GwNxorPfkcWvYDX09R3kSh-XzvCb1PN5g6vz7WrvaUjTPcYbqPNUhNmB_U13kRu2S_lKU7MMlmTgWYtoD8asLIi66O2zlhvZIgT329p5niexnqzJHZGSKDfnoyCKnr5HmOnoLBFveTtK3-EmYflimYmjN3n4WjB9YYhCOHRZVyHN-XqQawG4r-C3QXMtTgeMTbD4cRSZLpU2QQu6vLv1ClNUxED4BTBlGTp8vLIdUhiDrzx7nX1jEmZMtsfTodf-7_RL7L4eGbF02_TlXdhFAK2kIZacP14YJYo1i3PbKalg
INFO:root:Current server time: 2024-05-11 15:53:27.478159
INFO:root:Current server time: 2024-05-11 15:53:34.900235
INFO:root:Current server time: 2024-05-11 15:53:41.664224
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:Current server time: 2024-05-11 16:11:50.381516
INFO:root:Current server time: 2024-05-11 16:11:54.836064
INFO:root:Current server time: 2024-05-11 16:11:56.436856
WARNING:django.request:Not Found: /favicon.ico
INFO:app.my_middleware:Facebook callback received with code: AQAMZQi6nWC8pEl_BuLDZC9hUdKmxALeXWQsaEHHbTHESsxRUWB0i1SE5PHw92cp2tUgFrhNz87NSIQmfl4s9I4jwVziy1qGInTUNsuJ6sGcuOlXgbh3dQ85seSKTAD88DOGgacqIpcXpCqPL236qnWDLH4rSEhylevQByTE52AtrX7RRfMFUX-ab1-MUrFvPfkg3UIZKSLGMP-X7p96F29R6s0d6eJpN4cqpQOlsU0PH5c0pA2nL0rDU7Qu14cyxsfnnKhL7KuoAnv3U8g62Wh7T29-CKJAHRUHjSowloZfl86wbLkqFc69BVMxSKUjlsSIUXXVubSDg2xCGtlD_4TXmBCo_xBbyhPTq-aw6iojjIOSdGHvJQ_LYHMOWDoVmauEWDmjd3UJyN6FOwTjMueFwDC0p4ZWyf9lIVvqDtlBvQ
INFO:root:Current server time: 2024-05-11 16:12:19.332860
INFO:root:Current server time: 2024-05-11 16:12:25.769650
INFO:root:Current server time: 2024-05-11 16:12:32.675759
INFO:root:Current server time: 2024-05-11 17:36:03.319824
INFO:app.my_middleware:Facebook callback received with code: AQAWEVLGC2xIrA4rkICU2O9_JezbIuix2Ol2bmI0migRee1glokIMSf0Uj0A8_kIQctT6fRLJDD6ldopP0pm3Tk80fmT36ClfQORQ2BBsdraBinoxbyRbT_Z8X2k8j6TCWVikhhdaxuwjzq6hCRbDlYrjZimZKp-y3n0Thw4UxY9BMe96jq7O2J2RR8qnW1swfmHETR7Ty5LnMMz0kIJ9HSqtuq48aj42N9GlW2Vh9hx_jR0UXZ1yzhpR5nNrSMW3H1hvIOjuTEn9Xp9o5ic5ge1e3uy3SO4ashx8pFWcTlREXs9sEcMBS-TZIExlWLqALULz6-5hkwaHjxSdbmG_QywbCVunxE7yH9MPXNCiS_pJU77_FxVi6GfECUuh27EYkcDdPrJwE_XNTYV767kXiJqfU5tNnGqW6u5zbNoKy2pkw
INFO:root:Current server time: 2024-05-11 17:36:20.315048
INFO:root:Current server time: 2024-05-11 17:36:26.873947
WARNING:django.request:Not Found: /categories/
WARNING:django.request:Not Found: /categories/
WARNING:django.request:Not Found: /favicon.ico
INFO:root:Current server time: 2024-05-11 18:05:29.495659
INFO:root:Current server time: 2024-05-11 18:05:39.132907
INFO:root:Current server time: 2024-05-11 18:05:44.201447
INFO:root:Current server time: 2024-05-11 18:05:45.417473
INFO:root:Current server time: 2024-05-11 18:05:48.165074
INFO:root:Current server time: 2024-05-11 18:05:54.063297
WARNING:django.request:Not Found: /favicon.ico
INFO:root:Current server time: 2024-05-11 18:08:10.314565
INFO:app.my_middleware:Facebook callback received with code: AQDMSFFALACuzsIaWWDR4IXByDuYCtW44kg2CCnpz0lQDevMr23gdjgYEUhF21DY96FM8qzMyRLSyf8QsUaa5kt8gu_L6JUAKP_hSUJPMP6dm6vvM9r22nRYKboaAuwQ1Azwuiw6P6H4XVvDAkdXQyGvGMjwtYlRqBA1CmOZt7dZmHjR2RhulsUDAtv-FG4hEOoAZmOXR_OQ3ebwijV3VG1f7qQYzI3PebjBmJUt0_K-EkWzc5VKDCIhxbRISwvEunHg4SSQmgrmob9Vh1mPU4la7lwxUsghOs7Cl4-S1LuX9GRAU_rdjxu7HkIawmc4hKvsYhOAPdQ7pCg2gHcadY1LSLfErgqUYjUGU1T3PPa-O6eNpfl1eCWQS7q_TjEu3VwkH15m9LpqmqkmC73kh5_rLquQsFY3vdYslGIqvY4_aw
INFO:root:Current server time: 2024-05-11 18:08:19.889384
INFO:root:Current server time: 2024-05-11 18:08:46.010485
INFO:root:Current server time: 2024-05-11 18:08:58.475131
INFO:root:Current server time: 2024-05-11 19:05:07.708711
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:Current server time: 2024-05-11 20:40:23.533145
WARNING:django.request:Not Found: /favicon.ico
INFO:root:Current server time: 2024-05-11 20:41:03.362083
INFO:root:Current server time: 2024-05-11 20:41:09.167912
INFO:root:Current server time: 2024-05-11 20:41:09.744424
INFO:root:Current server time: 2024-05-11 20:41:10.024261
INFO:app.my_middleware:Facebook callback received with code: AQBgFowbVAoeU6k2DcTMzGhFt9dwFlKCSbA0oHpC_dlRUyjbKXvfKE_YEOGOUXYxyyffPqizV3kQIXxNdgUQHVi8uqdF_9yrL2VnufWyWUUfQIYpDWOzCINdG6hsghuEIkHm6F6p4p9xu1SfPOjIysl8Oq4DHcGkQXSNvMHAz3Zi5fK0WPjxfc69OodzWPu88CEVI1zAFnWELNt_ytUvveHH98WUItdPE9BCcFDSOH5tBiM9t2WeEI8BA1zvRf7OnWgc7MRmdrQcz7fUFUSIO0ZmSbQoNKlwJboHD_l1bhV4t1cMAm_5Suj6AWtzdp956z3wNUVhEUkiCjRQhswnFqmGHMy_dDh-HCDWv0lE96KAogA3NaPxHmKXbnNMkjXZtxH9PwHC1mqNa_yPKbvvb5ty8icuUh-4iw66iH9CzIsk1Q
INFO:root:Current server time: 2024-05-11 20:41:23.376706
INFO:root:Current server time: 2024-05-11 20:41:36.408124
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:Current server time: 2024-05-12 10:12:48.769168
WARNING:django.request:Not Found: /favicon.ico
INFO:root:Current server time: 2024-05-12 10:28:06.947559
INFO:root:Current server time: 2024-05-12 10:28:08.804117
INFO:root:Current server time: 2024-05-12 10:28:12.706990
INFO:root:Current server time: 2024-05-12 10:28:14.812345
WARNING:django.request:Not Found: /favicon.ico
INFO:root:Current server time: 2024-05-12 10:28:24.946040
INFO:root:Current server time: 2024-05-12 10:28:29.750210
WARNING:django.request:Not Found: /favicon.ico
INFO:app.my_middleware:Facebook callback received with code: AQCX1a2yZqm1kom3tK6wigAtQVwHAH9iJHNltgY4-DleAcMUjC6ohdhpQONkgjdND68tOpbKpPpspa7zenEDNWBYjY47i353zRbzcI4fm5KP7EIvhQ9UyqQC0Q-eyVlcKrY0fgFdw-85KVp-GFdCTPUwmiZ0teYopGo2mRf1wb1sYfvczSj_1Ooinx6MNhtztKq0p7F9bauIeeXM6xOshJ1Qv48i92pJssQUM1lbi7aB83Cqnvs2SSaEyPkbIvIee02mRNpMTRLiJJxU1gxBgqA_6LiRkCNXxbvyz9MAHTk8C4H8bY60gjeCDahRhOOPXfIFhgqD8yfaCfaGVlb0iZpYJiLbPqLS_FKyrnKWDH9FDsEVfaGGtLoWLMynF808IOQ5EGSW3uX_bf6qsTSp0ORvWE_m2rYbdY1vo7OiR3h6jg
INFO:root:Current server time: 2024-05-12 10:30:34.004397
INFO:root:Current server time: 2024-05-12 10:30:35.721398
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /categories/
WARNING:django.request:Not Found: /categories/
WARNING:django.request:Not Found: /favicon.ico
INFO:root:Current server time: 2024-05-12 12:43:33.364267
INFO:root:Current server time: 2024-05-12 13:25:03.915085
INFO:root:Current server time: 2024-05-12 13:25:05.713097
INFO:root:Current server time: 2024-05-12 13:26:52.323103
INFO:root:Current server time: 2024-05-12 13:26:53.998227
